"""
Data module for the second Saudi TikTok creator-scouting batch: 24 NEW
candidates (13 e-commerce + 11 trading), sourced independently from the
first batch in build_tiktok_scout.py and excluding every handle already
used there. Real estate was out of scope for this batch (trading/e-commerce
only, per request).

Sourced the same way as the first batch: no direct TikTok/X/Instagram/
Snapchat scraping was possible (the environment's egress proxy blocked
every one of those domains for direct fetches), so every candidate was
found and cross-verified via WebSearch snippets/titles and any
independently-reachable secondary source (press, personal sites, listing
platforms). Unknown fields are "n/a" — never guessed. Nationality-uncertain
or thin/bare-handle candidates are flagged rather than silently dropped or
excluded.

Only 24 of the requested 25 candidates cleared the verification bar within
the research budget spent on this batch (see build_tiktok_scout_batch2.py /
METHOD_NOTES2 for the shortfall note) — no 25th name was invented to hit
the round number.
"""

CANDIDATES2 = [
    # ---------------- E-COMMERCE (13) ----------------
    dict(name="فيصل صالح / Faisal Saleh", category="E-commerce",
         handle="@faisaleh22",
         niche="Dropshipping / affiliate-marketing training (\"business & dropshipping world\"), TikTok Shop ads, business-training courses",
         credentials="Runs two training platforms (fsaleh.com, faisaleh.com); self-described e-commerce & affiliate-marketing expert / certified trainer",
         socials="X @3eslan; fsaleh.com; faisaleh.com",
         followers="~1.1M-1.3M per search-engine snippet (not independently re-verified via direct TikTok access)",
         why_fit="Real named individual with two of his own branded training sites, a long-standing X handle, and content squarely in the dropshipping/affiliate-marketing e-commerce niche",
         risk_flag="Sells paid training/courses — verify no misleading income claims",
         depth_confidence="Medium-High — real name, own business sites, X handle cross-referenced; follower/like figures could not be independently re-verified (no direct TikTok access this pass)",
         sources="https://www.tiktok.com/@faisaleh22 ; https://x.com/3eslan ; https://fsaleh.com/ ; https://faisaleh.com/",
         status=""),
    dict(name="مرزوق البريك / Marzouq Al-Breik", category="E-commerce",
         handle="@mrz_s1", niche="TikTok Shop affiliate-marketing commissions, \"how to earn from TikTok\" tutorials",
         credentials="n/a beyond content itself", socials="n/a found beyond TikTok", followers="n/a",
         why_fit="Multiple videos explicitly hashtagged #السعودية #الرياض #جدة, real tribal surname (Al-Breik), consistent affiliate-marketing-for-e-commerce niche across several videos",
         risk_flag="\"Join my affiliate team\" style content — verify it isn't a pyramid/MLM-style recruitment scheme",
         depth_confidence="Medium — name + Saudi-city hashtags corroborate a Saudi base, but no second platform found to independently cross-confirm identity",
         sources="https://www.tiktok.com/@mrz_s1 ; https://www.tiktok.com/@mrz_s1/video/7275370598501551361 ; https://www.tiktok.com/@mrz_s1/video/7471668050010344712",
         status=""),
    dict(name="سلة / Salla (official)", category="E-commerce",
         handle="@sallaapp",
         niche="Official account of Salla, Saudi Arabia's largest e-commerce-enablement platform (store building, Salla-TikTok Shop integration, merchant affiliate-marketing tips)",
         credentials="Makkah-founded 2016 by Nawaf Hariri & Salman Butt; ~$7B GMV processed, 50,000+ merchants, $130M pre-IPO round (2023)",
         socials="salla.com; changelog.salla.sa; help.salla.sa", followers="~19.1K per search snippet",
         why_fit="Dominant, extensively documented Saudi e-commerce-platform brand — directly on-topic for \"Salla store setup\" niche",
         risk_flag="", depth_confidence="High (brand, not individual)",
         sources="https://www.tiktok.com/@sallaapp ; https://www.entrepreneur.com/en-ae/starting-a-business/saudi-unicorns-how-makkah-based-salla-is-helping-merchants/478045 ; https://arabfounders.net/en/nawaf-hareeri-salla-saudi-ecommerce/",
         status="Note: company/platform account, not an individual creator"),
    dict(name="خبراء المنصات / Salla Platform Experts", category="E-commerce",
         handle="@sallatips", niche="Salla store setup & design services, e-commerce store optimization for Saudi merchants",
         credentials="Agency site salatips.com/en/ — \"design and setup of e-commerce stores\" for Salla merchants",
         socials="salatips.com/en/", followers="n/a",
         why_fit="Named, documented Salla-focused e-commerce service brand with content matching the niche exactly",
         risk_flag="", depth_confidence="Medium (brand/agency, not an individual)",
         sources="https://www.tiktok.com/@sallatips ; https://salatips.com/en/",
         status="Note: agency/brand account, not an individual creator"),
    dict(name="سوشيال تيم / Social Team", category="E-commerce",
         handle="@sociall_team",
         niche="E-commerce store setup (Salla, Zid, Shopify, WooCommerce) + niche-selection advice for the Saudi market",
         credentials="Agency site social-team.net/sa-ar/, self-described Saudi digital-marketing company",
         socials="social-team.net/sa-ar/", followers="n/a",
         why_fit="Video content walks through \"best e-commerce niches in the Saudi market 2026\" — directly on-topic",
         risk_flag="", depth_confidence="Medium (brand/agency, not an individual)",
         sources="https://www.tiktok.com/@sociall_team/video/7606828370122362168 ; https://social-team.net/sa-ar/",
         status="Note: agency/brand account, not an individual creator"),
    dict(name="طارق العربي / Tariq Al-Arabi", category="E-commerce",
         handle="@al.araby85",
         niche="How to open/register an e-commerce business in Saudi Arabia (investment licenses, commercial registration for e-commerce)",
         credentials="n/a beyond content itself", socials="n/a found", followers="n/a",
         why_fit="Two separate videos found specifically on Saudi e-commerce business setup/licensing/cost — squarely on-topic niche",
         risk_flag="Gives quasi-legal/regulatory guidance on commercial registration — verify accuracy before outreach",
         depth_confidence="Flagged — nationality uncertain: one video caption pairs Saudi/Egyptian flags, suggesting an Egyptian professional advising on the Saudi market rather than confirmed Saudi nationality",
         sources="https://www.tiktok.com/@al.araby85/video/7605201283083029780 ; https://www.tiktok.com/@al.araby85/video/7541812530583211282",
         status="Flag: nationality uncertain (possible Egyptian professional operating in/advising on the Saudi market)"),
    dict(name="كيركي / Keerki Limited", category="E-commerce",
         handle="@keerki.limited",
         niche="China-sourcing/import tutorials and shipping services for Arab traders (import/sourcing sub-niche)",
         credentials="Registered trading/consulting company (Hong Kong-registered per its own About page, Guangzhou office); LinkedIn lists \"Nasir Abakar\" as founder",
         socials="keerki.com; store.keerki.com; instagram.com/keerki.limited (~108K per one snippet); youtube.com/@keerki.limited",
         followers="n/a on TikTok",
         why_fit="Import/sourcing-from-China content is one of the explicitly requested e-commerce sub-niches",
         risk_flag="Company/brand account; markets itself to \"Arab importers\" broadly, not Saudi-specifically",
         depth_confidence="Flagged — both market-focus (pan-Arab, not Saudi-specific) and founder-nationality concerns: founder name does not read as Saudi, no source ties leadership to Saudi Arabia beyond a claimed regional presence",
         sources="https://www.tiktok.com/@keerki.limited ; https://www.keerki.com/en ; https://cn.linkedin.com/in/nasirhedi ; https://store.keerki.com/pages/about-us",
         status="Flag: pan-Arab market focus and founder nationality both unconfirmed as Saudi — include with caution"),
    dict(name="Sara (\"ecom_sara\")", category="E-commerce",
         handle="@ecom_sara", niche="E-commerce/online-store marketing content, freelancing + Salla-style store-platform hashtags",
         credentials="n/a", socials="n/a found", followers="n/a",
         why_fit="On-topic e-commerce content niche; only verifiable TikTok presence found for this search angle",
         risk_flag="", depth_confidence="Low — no biographical detail, full name, or nationality confirmation found beyond the bare handle",
         sources="https://www.tiktok.com/@ecom_sara/video/7600279097725488405",
         status="Insufficient verification — bare handle only"),
    dict(name="iFast (\"ifast.sa\")", category="E-commerce",
         handle="@ifast.sa", niche="E-commerce-for-beginners content — TikTok business-account verification tips for small online stores",
         credentials="n/a", socials="n/a found", followers="n/a",
         why_fit="Explicitly hashtagged beginner e-commerce / online-store / small-project tags — on-topic beginner e-commerce content",
         risk_flag="", depth_confidence="Low — unclear whether individual or small-business account; no name/nationality found",
         sources="https://www.tiktok.com/@ifast.sa/video/7290119503982120200",
         status="Insufficient verification — bare handle only, individual vs. brand unclear"),
    dict(name="متجر سلطان للمنتجات الرقمية / Sultan D Store (Sultan Magfory)", category="E-commerce",
         handle="@sultan_d_store", niche="Digital-products e-commerce (productivity/school tools sold as downloadable products)",
         credentials="Store claims 16,000+ customers, 20,000+ orders; tied to domain sultan-magfory.com and a related TikTok account tag \"سلطان مجفوري\"",
         socials="X @sultan_d_store; Instagram @sultan_d_store; sultan-magfory.com", followers="~12.2K per search snippet",
         why_fit="Named store with a traceable owner-name lead (Magfory) and cross-platform presence (X, Instagram, TikTok, own domain)",
         risk_flag="", depth_confidence="Medium-Low — cross-platform presence is real, but this is a digital-products storefront rather than an e-commerce educator; personal nationality not independently confirmed",
         sources="https://www.tiktok.com/@sultan_d_store ; https://x.com/sultan_d_store ; https://www.instagram.com/sultan_d_store/ ; https://www.tiktok.com/@sultan_magfory/video/7462461186664058119",
         status="Note: digital-products store, adjacent niche rather than core dropshipping/e-commerce education"),
    dict(name="\"Badr\" (marketingwithbadr)", category="E-commerce",
         handle="@marketingwithbadr", niche="TikTok marketing / e-commerce advertising-campaign tips (\"how to sell your products on TikTok\")",
         credentials="n/a — a full personal name surfaced only in an unsourced AI search summary with no supporting snippet, so no name is asserted here",
         socials="n/a found", followers="n/a",
         why_fit="On-topic digital-marketing-for-e-commerce content niche",
         risk_flag="", depth_confidence="Low — bare handle; identity, nationality and credentials unverified",
         sources="https://www.tiktok.com/@marketingwithbadr/video/7509918191267728658",
         status="Insufficient verification — bare handle only; do not attach any name beyond the handle itself"),
    dict(name="\"the_etchh\"", category="E-commerce",
         handle="@the_etchh", niche="TikTok Shop / dropshipping education — opening a US TikTok Shop account and selling in America while living abroad",
         credentials="n/a", socials="n/a found", followers="n/a",
         why_fit="Dropshipping/TikTok Shop education content in Arabic",
         risk_flag="Teaches entering the US TikTok Shop market rather than the Saudi market — audience may include Saudis but the taught business target is the US",
         depth_confidence="Low — nationality and Saudi-audience targeting both unconfirmed",
         sources="https://www.tiktok.com/@the_etchh/video/7415207986513120529",
         status="Flag: content targets the US TikTok Shop market rather than the Saudi market specifically — possible niche mismatch"),
    dict(name="\"mih.1m\"", category="E-commerce",
         handle="@mih.1m", niche="China-to-Saudi-Arabia shipping/import logistics content (Jeddah Islamic Port, King Abdullah Port)",
         credentials="n/a", socials="n/a found", followers="n/a",
         why_fit="Directly on-topic for the import/sourcing-tutorials-aimed-at-Saudi-audiences niche, explicitly names Saudi ports",
         risk_flag="", depth_confidence="Low — bare handle; no name, nationality, or credentials found",
         sources="https://www.tiktok.com/@mih.1m/video/7665005291825663252",
         status="Insufficient verification — bare handle only"),

    # ---------------- TRADING (11) ----------------
    dict(name="د. أحمد المكلف / Dr. Ahmed Al-Moklaf", category="Trading",
         handle="@ph_moklaf",
         niche="Saudi stock market (Tadawul) education — beginner portfolio-building, dividend-company lists, IPO explainers, index-app referrals",
         credentials="Self-described investment advisor & certified trainer with 10+ years as a professional trader/investment advisor (per his nosooh.com advisor profile); provides financial advisory to listed/non-listed Saudi companies",
         socials="X @ph_moklaf; Snapchat @ahmed.moklaf; nosooh.com/advisor/760; guest commentator on an Al-Arabiya FM segment on Saudi investment regulations",
         followers="n/a",
         why_fit="Real named individual, consistent Eastern-Province/Al-Ahsa hashtag signal across dozens of videos, cross-verified via 3 independent properties beyond TikTok (X, Snapchat, nosooh.com) plus a mainstream-media appearance",
         risk_flag="Bio links to an investment-index registration/referral — verify this isn't an undisclosed paid-signal arrangement",
         depth_confidence="High — real name, doctoral title, 3+ independent corroborating sources",
         sources="https://www.tiktok.com/@ph_moklaf ; https://x.com/ph_moklaf ; https://www.snapchat.com/@ahmed.moklaf ; https://nosooh.com/advisor/760",
         status=""),
    dict(name="\"مس تاسي\" / \"Ms. TASI\"", category="Trading",
         handle="@ezdallaf", niche="Saudi stock market (TASI) commentary — dividend-stock lists, beginner tips, short explainer clips",
         credentials="n/a (persona/nickname account, no formal credentials found)",
         socials="Snapchat @ezdallaf — bio/location independently states Riyadh, Saudi Arabia; self-describes as a financial content creator/analyst",
         followers="n/a",
         why_fit="Rare female-fronted Saudi TASI-focused creator; Riyadh location confirmed on a platform beyond TikTok (Snapchat), consistent handle across both",
         risk_flag="", depth_confidence="Medium-High — real name not found (persona name only), but Saudi/Riyadh base independently corroborated via Snapchat",
         sources="https://www.snapchat.com/@ezdallaf ; https://www.snapchat.com/add/ezdallaf ; https://www.tiktok.com/@ezdallaf/video/7187336645937515778",
         status=""),
    dict(name="@ashomksa (handle-only)", category="Trading",
         handle="@ashomksa", niche="Detailed Saudi dividend-stock lists (quarterly/semi-annual payouts), Sharia stock-purity list reposts, quarterly-earnings recaps",
         credentials="n/a", socials="n/a found beyond TikTok", followers="n/a",
         why_fit="Extremely active, detailed, exclusively Saudi-market content (dozens of dividend/earnings videos, consistent Tadawul/Saudi-stock hashtag use)",
         risk_flag="Publishes detailed yield/stock lists without visible licensing disclosure",
         depth_confidence="Low-Medium — no personal name/bio/nationality confirmation beyond the TikTok content itself",
         sources="https://www.tiktok.com/@ashomksa/video/7530971100264598792 ; https://www.tiktok.com/@ashomksa/video/7548659103753587976 ; https://www.tiktok.com/@ashomksa/video/7636386892950359314",
         status="Flag: nationality/identity verified only via the account's own Saudi-market content focus, not an independent source"),
    dict(name="Sahm Capital (سهم كابيتال)", category="Trading",
         handle="@sahm_capital",
         niche="CMA-licensed brokerage platform — Saudi & US market trading tutorials, app walkthroughs, portfolio P&L reports",
         credentials="Full CMA (Capital Market Authority) license #22251-25; Riyadh-registered; first international online brokerage licensed for dealing/advisory/custody/fund management in Saudi Arabia (per multiple press releases)",
         socials="X @Sahm_Capital; Facebook \"Sahm Capital | Riyadh\"", followers="n/a",
         why_fit="Well-documented, CMA-licensed brand account — same acceptable pattern as the existing file's @aqarapp entry (brand, not individual, but best-verified in its category)",
         risk_flag="", depth_confidence="High (brand, not individual) — license number and press coverage independently confirm legitimacy",
         sources="https://www.tiktok.com/@sahm_capital/video/7517314408226295058 ; https://x.com/Sahm_Capital ; https://www.media-outreach.com/news/hong-kong/2024/10/15/333615/",
         status="Note: company/brand account, not an individual creator"),
    dict(name="د. علي بن حامد العمري / Dr. Ali bin Hamed Al-Amri", category="Trading",
         handle="@d.alialamri", niche="Mixed finance content — Saudi trading-platform comparisons, TASI investing tips (also touches e-commerce/tech topics)",
         credentials="Business trainer/consultant; columnist for Maal (a Saudi financial news site); runs a YouTube channel; self-described TASI investor",
         socials="X @Ali_Alomary / @draliamri; YouTube @alomareyTV; maaal.com author profile", followers="n/a",
         why_fit="Real named individual with a financial-press byline and dedicated TASI-investing TikTok videos, cross-verified via 3 platforms",
         risk_flag="Trading is one of several content themes rather than his exclusive niche — verify volume of dedicated trading content before outreach",
         depth_confidence="Medium — real name and press byline confirmed; niche breadth is a caveat",
         sources="https://www.tiktok.com/@d.alialamri/video/7651850824406158593 ; https://maaal.com/author/1616/ ; https://www.youtube.com/@alomareyTV ; https://x.com/ali_alomary",
         status=""),
    dict(name="\"صائد الأسهم الأمريكية\" / \"USA Stock Hunter\"", category="Trading",
         handle="@usastockhunter", niche="US stock market recommendations & education, day-trading tips, brokerage account-opening help",
         credentials="Self-described 10+-year US-stocks day trader/investor; runs a dedicated academy site",
         socials="Instagram, X, Telegram, Facebook, YouTube — all consistently branded \"usastockhunter\"; usastockhunteracademy.com",
         followers="n/a",
         why_fit="Extremely well cross-platformed with a long operating history and dedicated academy website",
         risk_flag="Sells paid stock 'recommendations'/signals without disclosed licensing — classic unlicensed-advice risk",
         depth_confidence="Low — Saudi nationality/base not found in any source; Arabic-language, pan-Gulf/pan-Arab audience, not confirmed Saudi specifically",
         sources="https://www.tiktok.com/@usastockhunter ; https://www.instagram.com/usastockhunter/ ; https://x.com/usastockhunter ; https://usastockhunteracademy.com/",
         status="Flag: nationality/Saudi base unconfirmed — included as a lead only, needs manual verification"),
    dict(name="محمد الحديثي / Mohammed Al-Hudhaithi", category="Trading",
         handle="@mhmh1199",
         niche="Saudi investment-fund education — IPO calendars, dividend fund comparisons, zakat-on-investment-funds calculators, brokerage-app promotion",
         credentials="n/a beyond content itself", socials="Instagram @mhmh1199 (bio locates account in Riyadh); X @mhmh1199",
         followers="~142.7K (336.9K likes, per search-indexed profile data)",
         why_fit="Real name, Riyadh base independently given on Instagram (not just TikTok), consistent dedicated finance-education niche across dozens of videos, cross-platform presence",
         risk_flag="Occasionally promotes specific fund products/app sign-ups — check for undisclosed paid placement",
         depth_confidence="Medium-High — real name + Riyadh location from a source beyond TikTok + consistent niche",
         sources="https://www.tiktok.com/@mhmh1199/video/7354382800499379457 ; https://www.instagram.com/mhmh1199/ ; https://x.com/mhmh1199",
         status=""),
    dict(name="عبدالله بن أحمد آل محسن / Abdullah bin Ahmad Al-Mohsen (\"حكيم السوق\")", category="Trading",
         handle="@alm0hsin",
         niche="Saudi stock technical analysis — daily support/target-level calls on individual TASI stocks, consistent \"not a recommendation\" disclaimers",
         credentials="n/a beyond content itself", socials="X @A_A_Almohsen (bio includes a Saudi flag)", followers="n/a",
         why_fit="Real full name with a tribal surname (Al-Mohsen), explicit self-identified Saudi flag on X, consistent nickname/brand (\"Market Sage\") across platforms",
         risk_flag="Daily buy/sell 'target' calls on individual stocks — verify these function as education rather than de facto unlicensed recommendations despite disclaimers",
         depth_confidence="High — real full name + independent Saudi self-identification on X + consistent cross-platform branding",
         sources="https://www.tiktok.com/@alm0hsin/video/7469505705402305799 ; https://x.com/A_A_Almohsen",
         status=""),
    dict(name="محمد أبو سدن / Mohammed Abu Saddan", category="Trading",
         handle="@msnk9990", niche="Saudi & US stock analysis — support levels/stop-losses tracked across roughly 50 stocks",
         credentials="n/a", socials="Snapchat @msnk9990", followers="n/a",
         why_fit="Consistent cross-platform handle (TikTok + Snapchat), dedicated stock-analysis format, explicit 'not a buy/sell recommendation' disclaimer",
         risk_flag="", depth_confidence="Medium — consistent handle across 2 platforms, but no independent nationality confirmation beyond Saudi-market content focus",
         sources="https://www.tiktok.com/@msnk9990/video/7542473978871352597 ; https://www.snapchat.com/@msnk9990",
         status="Flag: nationality inferred from content focus only, not independently confirmed"),
    dict(name="محمد السعيد / Mohammed Al-Saeed", category="Trading",
         handle="@md_alsaeed1", niche="Saudi stock analysis (e.g. Al-Rajhi Bank) and general financial-literacy content",
         credentials="n/a", socials="n/a found beyond TikTok (a similarly-named account also exists — not disambiguated)",
         followers="~43.2K (103.9K likes, per search-indexed profile data)",
         why_fit="Dedicated finance/stock-analysis content with concrete follower metrics",
         risk_flag="", depth_confidence="Low-Medium — no independent nationality confirmation beyond TikTok itself; possible duplicate/namesake handle unresolved",
         sources="https://www.tiktok.com/@md_alsaeed1",
         status="Flag: nationality unconfirmed beyond TikTok; possible namesake/duplicate account not disambiguated"),
    dict(name="ناصر العنزي / Nasser Al-Anzi (handle cluster, unconfirmed)", category="Trading",
         handle="@f7f7123f7 / @naserku87 / @naser_614 (unconfirmed which, if any, is his)",
         niche="CMA-licensed securities financial-advisor content — wealth management, retirement planning, portfolio structuring",
         credentials="CMA-licensed financial advisor (per nosooh.com); member, Saudi Economic Association; CISI ICWIM (international wealth-management) certified; financial columnist for Argaam, Maal, and Fortune Arabia",
         socials="nosooh.com/advisor/120", followers="n/a",
         why_fit="Strongest formal financial credentials of any candidate found (CMA license + international certification + financial-press column); search results describe him as active on TikTok",
         risk_flag="", depth_confidence="Low — multiple TikTok accounts share this common name and none could be confirmed as his; a Kuwaiti-flagged account with the identical name was confirmed to be a different (Kuwaiti) person",
         sources="https://nosooh.com/advisor/120 ; https://www.tiktok.com/@f7f7123f7 ; https://www.tiktok.com/@naserku87 ; https://www.tiktok.com/@naser_614",
         status="Flag: handle cluster — could not disambiguate the specific TikTok account; include as a lead only, needs manual verification"),
]

EXCLUDED2 = [
    dict(name="عبدالله الفوزان / Abdullah Al-Fawzan (Entrdemy)", category="E-commerce",
         reason="Confirmed to be the same individual as the already-used handle @econabdallah/@econabdullah; \"Entrdemy\" is his own dropshipping academy, not a distinct new candidate"),
    dict(name="Youssef Adel (@youssefadel_ecom)", category="E-commerce",
         reason="Dropshipping content explicitly hashtagged for the Saudi market, but the name reads as a common Egyptian name and no source confirms Saudi nationality — market-focus-vs-nationality trap risk"),
    dict(name="Ibrahim Al-Bahrawi (bhrawy.com)", category="E-commerce",
         reason="Well-documented \"best e-marketing expert in Saudi Arabia\" (20+ yrs experience, active content site) but no TikTok handle could be located despite multiple targeted searches — fails identifiable-TikTok-presence bar; surname also suggests possible non-Saudi (Egyptian) origin"),
    dict(name="Badr Shaker (@badrshaqer)", category="E-commerce",
         reason="Documented business/marketing figure (325K Instagram followers, business-admin + marketing-master's credentials, active on Threads) but no TikTok handle found"),
    dict(name="Saeed Badr", category="E-commerce",
         reason="Marketing consultant/Udemy instructor, co-founder of \"Markitia,\" active on Instagram, but no TikTok handle found"),
    dict(name="\"Omar تجارة الكترونية بالعربي\" (@markermji0f)", category="E-commerce",
         reason="Appears to be a duplicate/secondary handle under the identical brand name and bio as the already-excluded @maketingomar identity, not a distinct new individual"),
    dict(name="Faisal Al-Shathri (@faisxal33)", category="E-commerce",
         reason="Large TikTok following (~1.5M) but search results describe him as UAE/Dubai-based, not Saudi — namesake/wrong-country trap"),
    dict(name="Taher Alblowe (Rwaj)", category="E-commerce",
         reason="Genuine, Forbes Middle East-recognized Saudi live-shopping-app entrepreneur (covered by Arab News), but no personal TikTok creator handle located — fails identifiable-TikTok-presence bar"),
    dict(name="علي الحامد (@alialhamed.97)", category="Trading",
         reason="Re-surfaced independently during this pass; his own TikTok caption states he is a licensed financial influencer in the UAE — confirms this is the SAME person already excluded in the existing file for the UAE/wrong-country trap, not a new candidate"),
    dict(name="د. عمار ارحومة / Dr. Ammar Irhoma (@ammar.irhoma)", category="Trading",
         reason="Prominent Arabic Bitcoin/crypto educator with TikTok + YouTube + LinkedIn presence and Saudi-audience content, but his own LinkedIn confirms he is Dubai-based — market-focus-vs-nationality trap, not Saudi"),
    dict(name="ثامر الشهراني (@ithamer_77)", category="Trading",
         reason="One video promotes an investment app, but his consistent primary identity/niche is a physical-therapy specialist — wrong niche despite one trading-adjacent ad"),
    dict(name="طلال الأزهري (@talalalazhari)", category="Trading",
         reason="A TASI-stock hashtag surfaced adjacent to his content in search aggregation, but his actual TikTok content is entertainment/celebrity-news reporting — niche mismatch, not a trading creator"),
    dict(name="عمر العريفي (@omarsalarifi)", category="Trading",
         reason="638K-follower motivational 'happiness and success' creator who occasionally posts a paid ad for an investment fund — not a dedicated trading/investing-niche creator"),
    dict(name="سلوى الرشيد (X @Richs369)", category="Trading",
         reason="CMA-adjacent licensed financial advisor very active on X discussing TASI trades and technical analysis, but no TikTok handle could be located despite targeted searches — fails the identifiable-TikTok-presence bar"),
    dict(name="خبير اسهم (X @khabeer999)", category="Trading",
         reason="Jeddah-based stock commentator, 114K X followers, decade-long track record sharing daily TASI trend analysis, but only confirmed on X — no TikTok presence found"),
    dict(name="Al-Maqased Center pure-stocks list (Dr. Mohammed Al-Osaimi)", category="Trading",
         reason="Highly authoritative Sharia stock-screening source whose list is widely reposted by other TikTokers (e.g. @ashomksa), but no personal TikTok account for the Sheikh or his Center could be confirmed — fails identifiable-TikTok-presence bar for him personally"),
    dict(name="\"أبو نجود\" / Abu Nujood", category="Trading",
         reason="Aggregator descriptions credit him with Twitter/Telegram/TikTok presence and daily/weekly 'profitable stock' calls plus a paid course, but the exact TikTok handle could not be pinned down or verified — also carries a high unlicensed-signal-selling risk profile if confirmed"),
    dict(name="Fahad Al-Saud / Layla Al-Mutairi / \"Aisha\" (aggregator listicle)", category="Trading",
         reason="Named in an SEO 'richest Saudi forex traders' listicle with specific follower/wealth figures, but the source domain was unreachable for verification and no independent TikTok or other social handle could be found for any of the three — high risk of being generic SEO filler rather than real, findable individuals; excluded per the no-fabrication rule"),
    dict(name="\"yasmin.trader\" (forex/crypto content)", category="Trading",
         reason="Surfaced via a forex/crypto-strategy video, but no independent source ties the account to a Saudi nationality or base — could not clear the verification bar in the time available; not included as either a candidate or a confirmed exclusion, just not pursued further"),
]

METHOD_NOTES2 = [
    "This is the SECOND Saudi TikTok creator batch for this project (build_tiktok_scout.py holds the first 20 + 5 replacements). Scope for this batch: trading and e-commerce ONLY (no real estate), and every candidate had to be new — the 25 handles already used in the first batch were passed to the researchers as a hard exclusion list.",
    "Sourcing rule (same no-fabrication contract as the first batch): every claim needs a citable source URL; unknown fields are marked n/a, never guessed. Direct TikTok/X/Instagram/Snapchat page fetches (WebFetch) were blocked by this environment's egress proxy for every domain tried, so verification relied entirely on WebSearch snippets/titles — a harder verification ceiling than a live-browsing pass would have, same limitation the first batch's method notes flagged.",
    "Two parallel research passes ran, one per niche (E-commerce, Trading). The e-commerce pass returned 13 candidates. The trading pass exhausted its WebSearch call budget partway through and returned 11 candidates rather than the requested 13-15 — it explicitly declined to pad the list with unverified names to hit a target.",
    "A follow-up manual search pass (4 additional queries, covering forex/crypto and TikTok Awards MENA finance nominees) failed to surface one more clearable candidate, so this batch totals 24, one short of the requested 25. No 25th name was invented; the shortfall is reported here rather than concealed.",
    "'Depth/Confidence' column: the researching agent's own confidence in the verification (High/Medium/Low), separate from follower count or expertise depth — Low-confidence entries are included transparently rather than dropped, so treat them as leads needing manual follow-up, not settled picks.",
    "Three e-commerce entries (@sallaapp, @sallatips, @sociall_team) and one trading entry (@sahm_capital) are brand/agency accounts rather than individuals, included per the first batch's own precedent (it already accepted @aqarapp as a real-estate brand entry).",
    "Nationality flags: several candidates' Saudi nationality (vs. Saudi-market residency/focus) could not be independently confirmed — flagged per-row rather than silently included or excluded, same as the first batch.",
    "Trading-niche risk flags: several trading creators sell paid stock 'recommendations'/signals without disclosed licensing, or post daily buy/sell 'target' calls on individual stocks — flagged for compliance review before any outreach, not as a disqualification by itself.",
    "One entry (\"Nasser Al-Anzi\" handle cluster) is the strongest-credentialed trading candidate found (CMA license, international certification, financial-press column) but could not be matched to one specific TikTok handle among several same-name accounts — included as a flagged lead needing manual disambiguation, mirroring how the first batch handled its own 'Kingdom Real Estate' handle cluster.",
]
