#!/usr/bin/env python3
"""
Builds NH_Expert_Creator_Scout.xlsx — reconstructed from the archived
Northouse (NH) creator-scouting session transcript (2026-08-12/13).

Six parallel research agents scouted Saudi experts/creators across:
leadership, speaking, AI-for-professionals, personal finance, career
verticals (medical/nursing/accounting/PMP/etc.), and "hidden experts"
(high authority, near-zero online distribution). This script reassembles
their raw pipe-delimited findings (as reported back into the chat) into
one scored, filterable workbook.

Source: conversation_export_2026-08-13.txt (Slack file export of a prior
Claude Code session). The original working file built live in that
session is not recoverable — this is a faithful reconstruction from the
six agents' raw result payloads quoted in the transcript, not a re-run
of the research.
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

FONT_NAME = "Arial"

# ---------------------------------------------------------------------------
# Raw candidate data, transcribed from each scout agent's reported results.
# Fields: name, category, expertise, credentials, role, socials, followers,
# selling, activity, why_fit, depth, sources, status
# status: "" normal | "DQ: <reason>" | "Cross-listed: also found by <other scout>"
# ---------------------------------------------------------------------------

CANDIDATES = [
    # ---------------- LEADERSHIP (raw: 23) ----------------
    dict(name="د. محمد الخالدي / Dr. Mohammed Al-Khalidi", category="Leadership",
         expertise="Leadership + skills development training (survey-named)",
         credentials="PhD Strategic Mgmt–Inspirational Leadership, 2x Masters (HR; PM Bournemouth UK), TVTC-certified; 225,000+ trainees, 95+ orgs",
         role="Founder, Al-Nakhba Consulting + Al-Nakhba Training Accreditation Center; own academy drrmohh.com",
         socials="X @Moh_d_alkhaldi; Telegram t.me/drrmohh", followers="n/a",
         selling="Courses + consulting (own academy + rawa.com.sa bookings)", activity="active",
         why_fit="Survey-named, deep credentials, already productized but no funnel sophistication", depth=8,
         sources="https://drrmohh.com/aboutus ; https://www.rawa.com.sa/ar/expert/dr-mohammed-al-khalidi ; https://x.com/Moh_d_alkhaldi",
         status=""),
    dict(name="ياسر الحزيمي / Yasser Al-Huzaimi", category="Leadership",
         expertise="Soft skills / تطوير ذات / interpersonal leadership (survey-named)",
         credentials="~20 yrs; BA Arabic + BA psych counseling; certified British HR academies, Herrmann (HBDI), CoRT/DeBono; supervisor Majmaah Univ skills agency; author (الشخصية القوية)",
         role="Independent trainer/author; own podcast \"أ. ياسر الحزيمي\"",
         socials="X @YasserAlHzimi (clips @alhozimey)", followers="n/a",
         selling="Lectures/courses, books; bookable via rawa.com.sa", activity="active",
         why_fit="Mega-authority with employees ICP overlap; more self-dev than pure leadership; Guinness record فنجان ep = most-watched podcast ep ever on YouTube, 139M views", depth=8,
         sources="https://www.rawa.com.sa/ar/expert/mr-yasser-al-huzaimi ; https://x.com/YasserAlHzimi ; https://manhom.com/شخصيات/ياسر-الحزيمي/",
         status=""),
    dict(name="ريم بن صديق / Reem Bin Saddik", category="Leadership",
         expertise="Leadership (ILM-certified) + strategic marketing consulting (survey-named)",
         credentials="~13+ yrs; MBA (LAU Beirut); certified trainer, UK Institute of Leadership & Management (ILM) 2013–2017; award-jury member",
         role="Founder/CEO, Reem Bin Saddik Training & Marketing Consultancy (since 2017), Riyadh",
         socials="X @ReemBinSaddik; Snapchat reembs.coaching", followers="X 79.5K (seen)",
         selling="Consulting + training + coaching", activity="active",
         why_fit="Survey-named; female Saudi authority, already monetizing, Twitter-first", depth=7,
         sources="https://x.com/ReemBinSaddik ; https://www.snapchat.com/@reembs.coaching ; https://www.ithra.com/ar/speakers/reem-bin-saddik ; https://manhom.com/شخصيات/ريم-عمر-بن-صديق/",
         status=""),
    dict(name="بدر آل زيدان / Badr Al Zidane", category="Leadership",
         expertise="Media presenter/actor with self-dev interest",
         credentials="BA + MA special-needs education; ex-teacher; co-founder AI/creative group",
         role="Media personality; co-founder \"BCG Group for AI & Creative Solutions\"",
         socials="X @_BDRz; YouTube @badralzidane3514", followers="n/a",
         selling="Nothing visible in training/coaching", activity="active (media)",
         why_fit="Fails expertise-depth test", depth=3,
         sources="https://ar.wikipedia.org/wiki/بدر_آل_زيدان ; https://x.com/_BDRz",
         status="DQ: verified as media personality, not a leadership expert"),
    dict(name="د. إبراهيم بن حمد القعيد / Dr. Ibrahim AlQuayid", category="Leadership",
         expertise="Leadership & personal-effectiveness author-trainer (العادات العشر)",
         credentials="40+ yrs; PhD Education Indiana Univ (1983); consultant to gov + private sector; multiple leadership books",
         role="Chairman, Knowledge Group (Dar Al-Ma'rifah Human Development etc.), Riyadh",
         socials="n/a", followers="n/a",
         selling="Books (Jarir bestseller), corporate training, consulting; own site ibrahimalquayid.com", activity="rare/moderate",
         why_fit="Legacy mega-credibility, zero funnel — classic NH \"pure expert\" gold", depth=9,
         sources="https://ibrahimalquayid.com/en/book/the-10-habits-of-successful-people/ ; https://www.goodreads.com/author/show/2995640",
         status=""),
    dict(name="د. عبدالرحمن بن إبراهيم الدايل / Dr. Abdulrahman Al-Dayel", category="Leadership",
         expertise="Executive & leadership coaching",
         credentials="26+ yrs; PhD Administrative Leadership (Walden); MA HRM (Griffith); Marshall Goldsmith-certified + 14 intl coaching certs; 22,700+ coached, 89+ orgs; also seen: Oxford Exec Leadership, 80+ org clients, 17,000+ coached (Favikon leadership #14)",
         role="Founder, Tammakun Al-Awla consulting; university professor; executive coach, own practice (draldayel.com)",
         socials="LinkedIn linkedin.com/in/abdulrahman-al-dayel; X @draldayel; IG @draldayel; YouTube UC302-KBbmWuqRItSbcgVSxA",
         followers="n/a", selling="Coaching programs, training, consulting via draldayel.com", activity="active (all platforms)",
         why_fit="Best single fit found: deep Saudi exec-coach, full offer stack, weak funnel. Surfaced independently in BOTH the leadership sweep and the hidden-experts sweep — strongest convergence signal in the dataset.", depth=9,
         sources="https://draldayel.com/en/main/ ; https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia",
         status="Cross-listed: also found by Hidden-Experts scout"),
    dict(name="ناصر محمد العديلي / Nasser Aladaily", category="Leadership",
         expertise="Organizational behavior / HR / leadership (veteran author)",
         credentials="Decades (author of classic إدارة السلوك التنظيمي textbook); management & HR expert",
         role="Independent consultant/author (NMA)", socials="X @NasserAladaily", followers="n/a",
         selling="Books + consulting/training", activity="active on X",
         why_fit="Old-guard credibility every Saudi manager studied; untapped digitally", depth=8,
         sources="https://x.com/NasserAladaily ; https://www.neelwafurat.com/itempage.aspx?id=egb8891-5008906",
         status=""),
    dict(name="هدى الغصون / Huda Al-Ghoson", category="Leadership",
         expertise="Executive leadership / women-in-leadership (ex-Aramco)",
         credentials="35+ yrs Saudi Aramco, Executive Director of HR (first Saudi woman at that level); KSU + American Univ; exec ed Cornell/Michigan/Oxford; boards: STC, Bupa Arabia, JHAH; author \"Unbounded\" (2022)",
         role="Retired exec; author/speaker", socials="n/a", followers="n/a",
         selling="Book + paid speaking; no coaching offer visible", activity="rare",
         why_fit="Ultimate \"employees ICP\" credibility (Aramco HR chief); zero funnel = pure NH play", depth=9,
         sources="https://en.wikipedia.org/wiki/Huda_Al-Ghoson ; https://www.amazon.com/Unbounded-Huda-Al-Ghoson/dp/1911487590 ; https://energycouncil.com/event-speakers/huda-al-ghoson/",
         status=""),
    dict(name="د. ندى فدا / Dr. Nada Fida", category="Leadership",
         expertise="Leadership & resilience coaching; team coaching; EQ",
         credentials="20 yrs L&D; Senior Certified Transcendence Coach; EQi2.0/EQ360 certified; CCA faculty",
         role="President, ICF Saudi Arabia Chapter (2026); L&D consultant, Jeddah",
         socials="LinkedIn linkedin.com/in/dr-nada-fida-530a307/", followers="n/a",
         selling="Coaching + consulting", activity="active (LinkedIn)",
         why_fit="Sits atop Saudi coaching ecosystem; institutional authority", depth=8,
         sources="https://gulfmagazine.co/nada-fida-the-resilience-coach/ ; https://www.linkedin.com/in/dr-nada-fida-530a307/",
         status=""),
    dict(name="سهير الحاج / Suhair Alhaj", category="Leadership",
         expertise="Executive & career coaching, EQ",
         credentials="14+ yrs vocational training & mgmt; PCC, MBA, CCSP, Harrison Assessments, 360s; 900+ coaching hrs",
         role="Independent executive coach, Riyadh",
         socials="LinkedIn linkedin.com/in/suhair-alhaj-mba-ccsp-pcc-2287636a/", followers="n/a",
         selling="Coaching (Noomii, speaker bureau, Arab Coaching Forum)", activity="rare",
         why_fit="Credentialed female Saudi-market exec coach for employee ICP", depth=7,
         sources="https://www.noomii.com/users/suhair-alhaj ; https://www.icf-coaching.org/suhair-alhaj/profile/",
         status=""),
    dict(name="سعود ناصر العمير / Saud Nasser AlOmair", category="Leadership",
         expertise="Talent development / leadership coaching",
         credentials="CPTD, MBTI, ACC, BPS; ex-President ICF Saudi Chapter; ATD speaker",
         role="Talent development leader (ATD-affiliated), Riyadh",
         socials="LinkedIn linkedin.com/in/saudalomair/", followers="n/a",
         selling="n/a visible", activity="rare",
         why_fit="ICF/ATD institutional credibility, Arabic-native", depth=7,
         sources="https://www.linkedin.com/in/saudalomair/ ; https://www.menacoachingsummit.com/icf-saudi/",
         status=""),
    dict(name="سلمان أمجد / Salman Amjad", category="Leadership",
         expertise="Organizational coaching culture (Aramco)",
         credentials="PCC, CPCC, NLP Master Practitioner; coaching lead at Saudi Aramco; ICF Saudi board (innovation & development)",
         role="Coaching Lead, Saudi Aramco",
         socials="LinkedIn sa.linkedin.com/in/salman-amjad-pcc-cpcc-nlp-master-practitioner-7327a627", followers="n/a",
         selling="Nothing visible (employed)", activity="rare",
         why_fit="Aramco insider coach; verify Arabic delivery before outreach", depth=7,
         sources="https://icfsaudichapter.com/portfolio/salman-amjad/ ; https://icfconverge2023.eventscribe.net/fsPopup.asp?mode=presenterinfo&HPRID=1984005",
         status=""),
    dict(name="صبا الحربش / Saba Alherbish", category="Leadership",
         expertise="Executive coaching + leadership development",
         credentials="DBA Leadership Development, PCC, ATD Master Trainer",
         role="Freelance executive coach, Eastern Province KSA",
         socials="LinkedIn linkedin.com/in/sabaalherbish-1ba568b/", followers="n/a",
         selling="Freelance coaching", activity="rare",
         why_fit="Saudi female DBA+PCC — rare double credential", depth=7,
         sources="https://www.linkedin.com/in/sabaalherbish-1ba568b/", status=""),
    dict(name="سارة العتيبي / Sara Al-Otaibi", category="Leadership",
         expertise="Executive coaching (higher-ed sector)",
         credentials="ICF PCC", role="KAUST",
         socials="LinkedIn linkedin.com/in/saraalotaibi/", followers="n/a",
         selling="Nothing visible (employed)", activity="none/rare",
         why_fit="Saudi PCC at flagship institution", depth=6,
         sources="https://www.linkedin.com/in/saraalotaibi/", status=""),
    dict(name="بسمة بنت عبدالله بن شايق / Basmah bin Shayiq", category="Leadership",
         expertise="Neuroleadership + leadership skills",
         credentials="17+ yrs consulting & leadership dev; MA King's College London; Erickson Global certified; behavioral assessments",
         role="Founder of own consulting firm, Riyadh", socials="n/a", followers="n/a",
         selling="Consulting + training", activity="n/a",
         why_fit="Differentiated (neuroleadership) Saudi female founder", depth=7,
         sources="https://www.sauditrainers.sa/ابحث-عن-مدرب-بالمناطق/Riyadh", status=""),
    dict(name="عبير محمد الشعيبي / Abeer Al-Shueaibi", category="Leadership",
         expertise="Leadership skills + professional coaching",
         credentials="IPA (معهد الإدارة العامة) trainer since 2013; certified professional assessor + intl-certified coach",
         role="Trainer, Institute of Public Administration", socials="n/a", followers="n/a",
         selling="n/a (institutional)", activity="n/a",
         why_fit="IPA pedigree = instant credibility with government employees ICP", depth=6,
         sources="https://www.sauditrainers.sa/ابحث-عن-مدرب-بالمناطق/Riyadh", status=""),
    dict(name="أحمد حسن الحويكم / Ahmad Al-Hawaikam", category="Leadership",
         expertise="Organizational behavior + executive coaching",
         credentials="14 yrs; MA HR & Marketing (Univ. of Western Australia); 500+ programs, 10,000+ participants",
         role="Independent trainer, Riyadh", socials="n/a", followers="n/a",
         selling="Corporate training", activity="n/a",
         why_fit="Volume practitioner, no visible digital presence = whitespace", depth=6,
         sources="https://www.sauditrainers.sa/ابحث-عن-مدرب-بالمناطق/Riyadh", status=""),
    dict(name="أ.د. سالم بن سعيد القحطاني / Prof. Salem Al-Qahtani", category="Leadership",
         expertise="Administrative leadership (academic + author)",
         credentials="~30+ yrs; Professor, Public Admin, King Saud Univ; ex-Dean of Development KSU; author \"القيادة الإدارية: التحول نحو نموذج القيادي العالمي\"; teaches grad leadership course",
         role="Professor, KSU College of Business", socials="n/a", followers="n/a",
         selling="Book; academic", activity="none/rare",
         why_fit="The Saudi academic reference on القيادة الإدارية; zero productization", depth=8,
         sources="https://faculty.ksu.edu.sa/en/sqahtani ; https://dr-ama.com/?p=1532", status=""),
    dict(name="أ.د. عبدالله البريدي / Prof. Abdullah Al-Beraidi", category="Leadership",
         expertise="Management, org behavior, leadership, change mgmt",
         credentials="28+ yrs academia; Professor (Emeritus), Qassim Univ; award-winning author; strategic planning lead",
         role="Professor Emeritus, Qassim University", socials="n/a", followers="n/a",
         selling="Books", activity="rare",
         why_fit="Deep Saudi academic authority on leadership/change", depth=7,
         sources="https://ar.m.wikipedia.org/wiki/عبد_الله_البريدي ; https://www.researchgate.net/profile/bdallh-albrydy-Abdullah-Al-Beraidi", status=""),
    dict(name="إيهاب بدوي / Ihab Badawi", category="Leadership",
         expertise="Executive leadership coaching (MCC)",
         credentials="MCC (ICF); ex-CCO/VP/MD in retail/FMCG across MENA; coaches senior directors; founder Coaches Circle Academy",
         role="Founder, The Coaches Circle Academy (Lebanese, serves MENA/Gulf incl. Saudi)",
         socials="LinkedIn linkedin.com/in/ihabbadawi/", followers="n/a",
         selling="Coaching + coach training academy", activity="active (LinkedIn)",
         why_fit="Rare Arabic-speaking MCC with real corporate P&L history", depth=8,
         sources="https://thecoachescircleacademy.com/about-us/ ; https://icflebanon.org/portal/en-US/our-coaches/3/c/ihab-badawi-mcc/41/", status=""),
    dict(name="وسام الحداد / Wesam Al-Haddad", category="Leadership",
         expertise="Family business, board & executive development",
         credentials="20+ yrs; Six Sigma BB, CPT, CSP, certified business coach; 25,000+ trained, 250+ orgs, 15 nationalities",
         role="Executive Director, Ershad Business for Organizational Development (Amman; serves MENA)",
         socials="n/a", followers="n/a", selling="Consulting + training", activity="n/a",
         why_fit="Levantine serving GCC; verify Saudi client base before pursuing", depth=6,
         sources="https://ershadbusiness.com/cv", status="Flag: non-Saudi, GCC-serving"),
    dict(name="د. طارق السويدان / Dr. Tareq Al-Suwaidan", category="Leadership",
         expertise="Leadership & management training (Islamic-framed)",
         credentials="30+ yrs; PhD; author of many leadership books; full leadership course catalog",
         role="Owner suwaidan.com + Gulf Innovation Academy (Kuwaiti serving Gulf)",
         socials="X @TareqAlSuwaidan", followers="X 7.8M (seen)",
         selling="Online courses, live courses, books", activity="active",
         why_fit="Depth 10 but political sensitivities with Saudi audience (past Saudi backlash)", depth=9,
         sources="https://suwaidan.com/courses/مجموعة-دورات-القيادة/ ; https://x.com/TareqAlSuwaidan ; https://www.alhurra.com/kuwait/2023/04/19/",
         status="DQ: high reputational risk — past Saudi-market political backlash"),
    dict(name="د. عمرو الحداد / Dr. Amr Al-Haddad", category="Leadership",
         expertise="Executive coaching + leadership skill development for Saudi market",
         credentials="Publishes Saudi-specific leadership development guides; offers 1:1 certified coaching, 3–6 month executive programs",
         role="Founder, amrinsight.com", socials="n/a", followers="n/a",
         selling="Coaching + assessments + intensive programs", activity="active (SEO blog)",
         why_fit="Already targeting exact NH ICP (Saudi employees/leaders) with content", depth=6,
         sources="https://www.amrinsight.com/ar-SA/blogs/leadership-skills-development-saudi-arabia", status=""),

    # ---------------- HIDDEN EXPERTS (raw: 26; AlDayel & AlRuhaily cross-listed above/below) ----------------
    dict(name="مطلق المريشد / Mutlaq Al-Muraished", category="Hidden Experts",
         expertise="Executive management, crisis leadership",
         credentials="40+ yrs senior exec roles at major Saudi companies (\"رجل المهمات الصعبة\")",
         role="Retired executive", socials="none found", followers="n/a",
         selling="No", activity="rare",
         why_fit="Massive فنجان episode reach, 40-yr exec story, zero creator presence — classic NH front-man", depth=9,
         sources="https://thmanyah.com/post/1kh7zbdhgp_1jhggnmybp ; https://www.youtube.com/watch?v=UqThkg0wt7c", status=""),
    dict(name="عبدالرحمن الجضعي / Abdulrahman Al-Jadhai", category="Hidden Experts",
         expertise="Corporate leadership, scaling tech companies",
         credentials="19 yrs at Elm, rose through all ranks to CEO", role="Ex-CEO of Elm",
         socials="none found", followers="n/a", selling="No", activity="rare",
         why_fit="Ex-CEO of iconic Saudi tech co, deep credibility for career-ladder content, no social machine", depth=9,
         sources="https://thmanyah.com/post/1kv1jb3ra1_1jhggnmybp ; https://www.youtube.com/watch?v=qSNAcuN4ZZ0", status=""),
    dict(name="نايف الفهيد / Nayef Al-Fahid", category="Hidden Experts",
         expertise="HR, hiring, career progression",
         credentials="25 yrs as HR director", role="HR director",
         socials="none found", followers="n/a", selling="No", activity="none",
         why_fit="Exactly the \"how to get hired/promoted\" expertise Saudi employees pay for; invisible online. Also named by Haya in the kfahm survey.", depth=8,
         sources="https://www.youtube.com/watch?v=QPTwsoa47do", status=""),
    dict(name="عبدالرحمن الفاضل / Abdulrahman AlFadhel", category="Hidden Experts",
         expertise="Leadership, motivation, energy-sector careers",
         credentials="40 yrs Saudi Aramco (1982–2021), certified life coach",
         role="Retired Director, Aramco Riyadh Refinery",
         socials="LinkedIn (per Favikon); X @AA_ALFadhel", followers="n/a",
         selling="No (coaching informal)", activity="rare (X only)",
         why_fit="40-yr Aramco authority + already coach-minded, zero TikTok/IG — prime unsigned asset", depth=9,
         sources="https://www.youtube.com/watch?v=Ex7dZuR3EiA ; https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="عبدالله الجرف / Abdallah Aljurf", category="Hidden Experts",
         expertise="Leadership coaching, talent development",
         credentials="20+ yrs; ICF PCC, ATD CPTD; 1,200+ coaching hrs; clients: Aramco, Oracle, GE; Thinkers50 Goldsmith Award nominee 2019",
         role="GM Continuous Learning, Ministry of HR & Social Development",
         socials="LinkedIn linkedin.com/in/aljurf/; X @aljurf", followers="n/a",
         selling="Yes (coaching via ETIMY)", activity="active (LinkedIn)",
         why_fit="Elite coaching credentials, LinkedIn-only, no short-video presence to convert", depth=9,
         sources="https://www.menacoachingsummit.com/speaker/abdallah-aljurf/ ; https://etimy.com/all-coaches/business-coaching/executive-leadership-coach/abdallah-aljurf/", status=""),
    dict(name="عاصم الرحيلي / Asem Al-Ruhaily", category="Hidden Experts",
         expertise="Personal finance, wealth planning",
         credentials="20+ yrs financial sector; certified financial advisor; Saudi Economics Assoc member",
         role="Founder, Al-Ruhaily Financial Consulting",
         socials="X @AsemEcono; IG @asemecono", followers="n/a",
         selling="Yes (courses/consulting on alruhaily.com)", activity="active (podcast guesting)",
         why_fit="THE recurring personal-finance guest of Saudi podcasts (كاش, بترولي, توّاق, مهارات), no scaled B2C funnel. Surfaced independently in both the hidden-experts and finance sweeps.", depth=8,
         sources="https://www.youtube.com/watch?v=P8yaMH4AxTg ; https://alruhaily.com/ ; https://x.com/asemecono",
         status="Cross-listed: also found by Finance scout"),
    dict(name="خالد الخضير / Khalid Alkhudair", category="Hidden Experts",
         expertise="Employment, women's workforce inclusion, careers",
         credentials="Founded Glowork 2011; led KPMG to 25+ workplace awards; WEF Global Shaper",
         role="COO & Market Officer, KPMG (KSA/Kuwait/Jordan); Founder Glowork",
         socials="X @glowork (company)", followers="n/a", selling="No", activity="rare",
         why_fit="Saudi employment-market authority with global stage cred, no creator play", depth=8,
         sources="http://khalidalkhudair.com/ ; https://www.worldgovernmentssummit.org/ar/media-hub/speakers/detail/خالد-الخضير", status=""),
    dict(name="صفاء النعيم / Safa Al-Naeem", category="Hidden Experts",
         expertise="Insurance & investment leadership, women in finance",
         credentials="17 yrs insurance + 14 yrs executive management; first female chair/CEO in Saudi insurance",
         role="CEO, Al-Afdal Insurance", socials="X @safa3n", followers="n/a",
         selling="No (advisory)", activity="rare",
         why_fit="First-female-CEO story + finance depth = powerful program front for professional women", depth=8,
         sources="https://creators.spotify.com/pod/profile/ceoksa/episodes/ep-e2b9og2", status=""),
    dict(name="مدحت عامر / Medhat Amer", category="Hidden Experts",
         expertise="Management & leadership",
         credentials="30+ yrs; ex-Microsoft (\"worst manager\" → top-10 manager globally); Gartner executive partner",
         role="Executive Partner, Gartner", socials="none found", followers="n/a",
         selling="No", activity="none",
         why_fit="Huge فنجان reach, unforgettable manager-transformation arc, no personal channels", depth=8,
         sources="https://www.youtube.com/watch?v=9-mpp2dtidE", status="Flag: nationality n/a, Saudi-based/market-relevant"),
    dict(name="بدر العوجان / Bader Hamed Alaujan", category="Hidden Experts",
         expertise="Governance, strategy, leadership mentoring",
         credentials="CEO-level career, multiple board roles", role="CEO, Savola Foods",
         socials="LinkedIn (per Favikon)", followers="n/a", selling="No", activity="active (LinkedIn)",
         why_fit="Sitting CEO who mentors publicly — post-tenure program potential", depth=8,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="فؤاد الزهراني / Fouad Alzahrani", category="Hidden Experts",
         expertise="HR strategy, digital transformation", credentials="28+ yrs",
         role="Chief Shared Services Officer, SABIL", socials="LinkedIn (per Favikon)", followers="n/a",
         selling="No", activity="active (LinkedIn)",
         why_fit="28-yr HR exec = career-growth authority for employees, LinkedIn-only", depth=8,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="عبدالله النقيدان / Abdullah Alnegedan", category="Hidden Experts",
         expertise="Operations, career journeys at global firms",
         credentials="20+ yrs at Uber, Amazon, PwC, Saudi Binladin",
         role="Operations executive, entrepreneur", socials="LinkedIn/YouTube (per Favikon)", followers="n/a",
         selling="n/a", activity="active (LinkedIn/YouTube)",
         why_fit="\"Saudi who climbed Amazon/Uber\" story maps perfectly to employee-audience aspiration", depth=7,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="بندر أبوعشي / Bandar Abuashi", category="Hidden Experts",
         expertise="Executive leadership, Vision 2030 careers", credentials="25+ yrs",
         role="SVP Executive Office, Saudi Tourism Authority", socials="LinkedIn (per Favikon)", followers="n/a",
         selling="No", activity="active (LinkedIn)",
         why_fit="Senior government-adjacent exec, LinkedIn authority, zero short-form presence", depth=7,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="محمد مرغلاني / Mohammed Marghalani", category="Hidden Experts",
         expertise="C-suite leadership, hospitality/tourism/finance",
         credentials="C-suite + board member across sectors", role="Board member / C-suite executive",
         socials="LinkedIn (per Favikon)", followers="n/a", selling="No", activity="active (LinkedIn)",
         why_fit="Multi-sector exec authority, unmonetized", depth=7,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="عبدالعزيز بن دوين الجهني / Abdulaziz Bin Dwayen Al-Juhani", category="Hidden Experts",
         expertise="Behavioral leadership, security/discipline",
         credentials="Retired brigadier general; author", role="Security consultant, author",
         socials="n/a", followers="n/a", selling="Yes (consulting)", activity="rare",
         why_fit="Military-leadership author = differentiated discipline/leadership angle for Saudi men", depth=7,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="سارة الحجري / Sara AlHajri", category="Hidden Experts",
         expertise="Organizational excellence, strategy, project management", credentials="12+ yrs",
         role="Director at Darah (King Abdulaziz Foundation)", socials="LinkedIn (per Favikon)", followers="n/a",
         selling="No", activity="active (LinkedIn)",
         why_fit="Female Saudi PM/strategy director — underserved professional-women segment", depth=7,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="د. سلوى الحلافي / Dr. Salwa Alhalafi", category="Hidden Experts",
         expertise="Leadership behavior, self-efficacy, institutional excellence",
         credentials="PhD Lancaster University", role="Leadership consultant",
         socials="LinkedIn (per Favikon)", followers="n/a", selling="n/a", activity="active (LinkedIn)",
         why_fit="Credentialed female leadership voice, LinkedIn-only", depth=6,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="د. فياض العنزي / Dr. Fayadh Alenezi", category="Hidden Experts",
         expertise="Risk management, \"presilience,\" leadership",
         credentials="Risk transformation consultant", role="Risk Leadership Architect (independent)",
         socials="LinkedIn (per Favikon)", followers="n/a", selling="Yes (consulting)", activity="active (LinkedIn)",
         why_fit="Niche-but-corporate-valuable expertise; could front risk/leadership program", depth=6,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="خالد زيدان / Khaled Zedan", category="Hidden Experts",
         expertise="Operational excellence, digital transformation, F&B industry",
         credentials="Senior business leader", role="Business leader, F&B sector",
         socials="LinkedIn+X (per Favikon)", followers="n/a", selling="No", activity="active (LinkedIn)",
         why_fit="Ops-excellence practitioner voice, no consumer content", depth=6,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="عامر العجمي / Amer Al Ajmi", category="Hidden Experts",
         expertise="Strategic development, engineering & construction leadership",
         credentials="25+ yrs", role="C-suite executive, board member",
         socials="LinkedIn (per Favikon)", followers="n/a", selling="No", activity="active (LinkedIn)",
         why_fit="Engineering-career ladder authority (huge Saudi engineer audience)", depth=6,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="أحمد مدني / Ahmed Madany", category="Hidden Experts",
         expertise="Strategy, logistics, business transformation", credentials="15+ yrs",
         role="Executive Director, Mahasin Alsharq", socials="LinkedIn+YouTube (per Favikon)", followers="n/a",
         selling="n/a", activity="active",
         why_fit="Mid-career exec already experimenting with content — signable early", depth=6,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status=""),
    dict(name="باسم جفال / Basem Jaffal", category="Hidden Experts",
         expertise="Innovation, design thinking",
         credentials="IDEO U coach, Elm Company", role="Innovation Enabler, Elm",
         socials="LinkedIn (per Favikon)", followers="n/a", selling="n/a", activity="active (LinkedIn)",
         why_fit="\"Innovation at work\" angle for corporate employees, LinkedIn-only", depth=6,
         sources="https://www.favikon.com/blog/top-linkedin-influencers-saudi-arabia", status="Flag: nationality n/a, KSA-based"),
    dict(name="معتز صبجاقي / Moetaz Soubjaki", category="Hidden Experts",
         expertise="Performance strategy, HR keynotes",
         credentials="15,000+ professionals trained (Lebanese, KSA/GCC market)",
         role="Senior Manager, PwC Middle East", socials="LinkedIn (per Favikon)", followers="n/a",
         selling="Yes (training)", activity="active (LinkedIn)",
         why_fit="Proven trainer at scale; borderline (non-Saudi) but GCC-credible", depth=6,
         sources="https://www.favikon.com/blog/top-leadership-influencers-saudi-arabia", status="Flag: Lebanese, GCC-serving"),
    dict(name="خلود المانع / Kholoud Almani", category="Hidden Experts",
         expertise="Women's empowerment, leadership",
         credentials="UN-affiliated \"Women Empowerment Ambassador\" 2024; keynote at 7th World Human Rights Summit",
         role="Ambassador/keynote speaker", socials="some presence (n/a counts)", followers="n/a",
         selling="n/a", activity="active (speaking)",
         why_fit="International-stage authority for Saudi professional women vertical", depth=6,
         sources="https://www.rowadalaamal.com/خلود-المانع-سفيرة-تمكين-المرأة-في-2024/", status=""),
    dict(name="سالم العنزي / Salem Alanzi", category="Hidden Experts",
         expertise="Career success, professional development writing",
         credentials="Saudi author/writer, own career-advice publication site", role="Writer/consultant",
         socials="n/a", followers="n/a", selling="n/a", activity="rare",
         why_fit="Already writes career content Saudis search for; no distribution engine", depth=5,
         sources="https://salemalanzi.sa/build-a-successful-career/", status=""),

    # ---------------- FINANCE (raw: 16) ----------------
    dict(name="فهد الحويماني / Fahad Al-Hoymany", category="Finance",
         expertise="Financial markets & investing education (Tadawul + global)",
         credentials="20+ yrs; author \"المال والاستثمار في الأسواق المالية\" (sold at Jarir); Saudi Economic Association member",
         role="Independent financial markets expert / columnist, CNBC Arabia guest",
         socials="X @FahadAlHoymany; YouTube channel", followers="X 30.1K (seen)",
         selling="Partially (book; media)", activity="active",
         why_fit="Published Arabic personal-investing author + trusted media voice, zero funnel behind him", depth=9,
         sources="https://x.com/fahadalhoymany?lang=ar ; https://www.jarir.com/arabic-books-283911.html ; https://www.cnbcarabia.com/episode/1795", status=""),
    dict(name="خلود الدخيل / Khlood Aldukheil", category="Finance",
         expertise="Financial advisory, women's financial empowerment, corporate finance",
         credentials="25+ yrs; CFA (2003), MBA American Univ., BSc Georgetown; CFA Society Saudi board member",
         role="CEO/owner, Irtiqa Financial (إرتقاء المالية); chair of women's business council at Saudi Chambers",
         socials="X @kaldukheil", followers="n/a", selling="Advisory (B2B/B2C), no info products",
         activity="rare/active (columnist at Maaal)",
         why_fit="Elite credentials + female authority in a male-heavy niche = differentiated creator asset", depth=9,
         sources="https://x.com/kaldukheil?lang=en ; https://maaal.com/author/1552/ ; https://manhom.com/شخصيات/خلود-عبدالعزيز-الدخيل/", status=""),
    dict(name="ازدهار علاف / Ezdehar Allaf (\"Miss Tasi\")", category="Finance",
         expertise="Saudi stock-market (TASI) analysis + financial awareness for public",
         credentials="~10 yrs banking/media; Master's in insurance; first Saudi female financial markets analyst; Al-Ekhbariya presenter",
         role="Banking consultant + TV financial analyst; now leads a shareholder company (7,838 shareholders per her X)",
         socials="X @ezdallaf; IG @ezdallaf; TikTok @ezdehar2022", followers="n/a",
         selling="Unclear — trainer/consultant", activity="active (X, Snapchat, TikTok)",
         why_fit="Already a multi-platform finance educator with media credibility, un-systemized monetization; Snapchat-native fits NH's Snapchat-first pivot", depth=8,
         sources="https://x.com/ezdallaf ; https://rotana.net/السعودية-ازدهار-علاف-أول-سيدة-في-منتدى/ ; https://www.tiktok.com/@ezdehar2022", status=""),
    dict(name="صلاح خاشقجي / Salah Khashoggi", category="Finance",
         expertise="Halal investing for salary earners, fintech",
         credentials="15+ yrs investment & financial mgmt",
         role="Founder, Tamra Capital (تمرة المالية) — CMA-licensed halal robo-advisor, ~SAR 250M story",
         socials="X @salahkhashoggi", followers="n/a", selling="Yes (own platform)",
         activity="active (podcasts: Fenjan ep. \"كيف تستثمر راتبك لتعيش غنيًا\")",
         why_fit="The literal \"invest your salary\" authority in KSA; likely partner/JV not signable creator", depth=8,
         sources="https://open.spotify.com/episode/6qdmGir6YiBSMacyrFCEMd ; https://x.com/TamraCapital/status/1738418567564161114", status=""),
    dict(name="تركي فدعق / Turki Fadaak", category="Finance",
         expertise="Macro + Saudi capital markets analysis",
         credentials="25+ yrs (macro analysis since 2000); ex-Head of Research & Advisory, AlBilad Capital (2011–2019)",
         role="Independent economic/markets analyst, TV regular (Asharq Bloomberg, CGTN)",
         socials="X @TurkiFadaak", followers="n/a", selling="No info products seen", activity="active (media + X)",
         why_fit="Bank-grade research credibility convertible into employee-investor education", depth=8,
         sources="https://twitter.com/turkifadaak?lang=ar ; https://aawsat.com/home/article/1422821 ; https://www.expertsgulf.com/ar-sa/experts/628a7823-4217-488f-b0bc-78f54eb6ca63", status=""),
    dict(name="د. محمد علي القري / Dr. Mohammed Ali Elgari", category="Finance",
         expertise="Islamic finance / shariah-compliance of investments",
         credentials="40+ yrs; PhD; Assoc. Prof Islamic Economics KAU; AAOIFI Shariah Council; shariah boards of banks in KSA/Gulf/EU/US",
         role="Shariah board member (SNB Capital etc.); own site elgari.com",
         socials="n/a", followers="n/a", selling="No (academic/advisory)", activity="rare",
         why_fit="Ultimate halal-credibility moat as advisor/co-sign for NH finance offers (age ~75 — advisor role, not creator)", depth=10,
         sources="https://www.elgari.com/resume/ ; https://snbcapital.com/w/dr.-mohammed-ali-al-qari", status="Note: advisor/co-sign tier, not a creator signing"),
    dict(name="أحمد القصبي / Ahmad Kasabi", category="Finance",
         expertise="Simplifying markets, IPOs, VC, money topics in Arabic",
         credentials="Podcast host since ~2021", role="Host, بودكاست فلوس (Floos Podcast)",
         socials="X @AhmadKasabi", followers="n/a", selling="No products seen", activity="active",
         why_fit="Proven Arabic money-content engine, format ready for offerization", depth=7,
         sources="https://podcasts.apple.com/sa/podcast/بودكاست-فلوس/id1551767510 ; https://x.com/AhmadKasabi?lang=en", status=""),
    dict(name="فهد الفهيد / Fahad Al-Fahaid", category="Finance",
         expertise="Savings/financial-awareness training (الوعي الادخاري)",
         credentials="Master's in business administration; leads licensed nonprofit (license 2250, est. 2022)",
         role="Executive Director, جمعية الادخار (Saudi Savings Association)",
         socials="LinkedIn sa.linkedin.com/in/فهد-الفهيد-15570a94; X (org) @JAledkhar1", followers="n/a",
         selling="Nonprofit courses/workshops", activity="active (via association)",
         why_fit="Runs KSA's savings-awareness machine — trainer network + gov-adjacent trust", depth=7,
         sources="https://edkhar.org.sa/ ; https://x.com/JAledkhar1?lang=ar", status=""),
    dict(name="خالد الرويلي / Khalid Al-Ruwaili", category="Finance",
         expertise="Saudi stocks investing/trading training",
         credentials="Chairman of licensed training academy (kwealth.edu.sa)",
         role="Chairman & lead trainer, Kwealth / مفتاح الثروة للتدريب",
         socials="n/a", followers="n/a", selling="Yes — paid recorded + live cohort courses", activity="active (recurring cohorts)",
         why_fit="Already-monetizing course operator; CAUTION: \"المضاربة\" (speculation) framing needs compliance screen vs NH halal-credibility bar", depth=6,
         sources="https://kwealth.edu.sa/ ; https://kwealth.edu.sa/course/essentailskillrecorded", status="Caution: speculation-trading framing vs NH halal bar"),
    dict(name="مطر الشمري / Matar Al-Shammari", category="Finance",
         expertise="Real-estate & investment consulting", credentials="n/a",
         role="Real-estate/investment consultant (self-branded on X)",
         socials="X @mnfr10", followers="n/a", selling="Consulting, unclear products", activity="active",
         why_fit="Covers the عقار/تمويل عقاري gap in the niche; needs credential verification", depth=6,
         sources="https://twitter.com/mnfr10", status=""),
    dict(name="سعد العنزي / Saad Al-Anzi", category="Finance",
         expertise="Personal financial advisory (savings/investing)", credentials="n/a",
         role="Financial advisor, Riyadh — Snapchat-first creator", socials="n/a", followers="n/a",
         selling="Unclear", activity="active (Snapchat)",
         why_fit="Snapchat-native finance advisor = fits NH's Snapchat-first ad machine; verify licensing", depth=5,
         sources="https://www.snapchat.com/@sadmatr5?locale=ar", status=""),
    dict(name="(anon) صناديق المؤشرات الشرعية / index-fund account", category="Finance",
         expertise="Shariah index-fund investing / halal FIRE for Saudis", credentials="n/a (identity unknown)",
         role="Educational X account (Bogleheads-style, halal ETFs: SPUS, sukuk funds)",
         socials="X @indexfundksa", followers="n/a", selling="No", activity="active",
         why_fit="Exactly NH's ICP thesis (salary→halal index funds); DM to unmask & assess operator", depth=7,
         sources="https://x.com/indexfundksa", status="Anonymous account — identity unverified"),
    dict(name="(anon) خبير تقاعد / retirement account", category="Finance",
         expertise="GOSI/retirement-system optimization Q&A", credentials="n/a (identity unknown)",
         role="Personal X account answering Saudi pension/GOSI questions",
         socials="X @spension", followers="n/a", selling="No", activity="active",
         why_fit="Owns the retirement/GOSI micro-niche nobody else teaches; unmask via DM", depth=6,
         sources="https://x.com/spension", status="Anonymous account — identity unverified"),
    dict(name="أحمد كردي / Ahmad Kordi, CFA", category="Finance",
         expertise="Investment profession / financial analysis",
         credentials="CFA charterholder; society president", role="President, CFA Society Saudi Arabia",
         socials="n/a", followers="n/a", selling="No", activity="none",
         why_fit="\"Pure expert, zero social\" archetype with instant credential moat; also gateway to 100s of Saudi CFAs (board incl. Mona Alnemer, Rawan Aljermawi)", depth=7,
         sources="https://www.cfasociety.org/saudiarabia/about-us/leadership", status=""),
    dict(name="(org) استثمر بوعي / InvestWiselySA", category="Finance",
         expertise="Investor-awareness education workshops", credentials="n/a",
         role="Educational account @InvestWiselySA", socials="X @InvestWiselySA", followers="n/a",
         selling="Workshops", activity="active",
         why_fit="Pipeline source for licensed trainer names behind it — not itself a signable individual", depth=5,
         sources="https://x.com/InvestWiselySA?lang=ar", status="Org/lead-source account, not an individual creator"),

    # ---------------- SPEAKING (raw: 17) ----------------
    dict(name="محمد القحطاني / Mohammed Qahtani", category="Speaking",
         expertise="Public speaking mastery, keynote & stage craft (Arabic+English)",
         credentials="~17 yrs; 2015 Toastmasters WORLD Champion of Public Speaking (only Arab ever), 9,000+ stage hours, 5x TEDx, 1,000+ engagements in 40+ countries; overcame severe stutter",
         role="Independent speaker/trainer \"Qahtani Speaks\"; formerly Saudi Aramco security engineer, Dhahran",
         socials="LinkedIn linkedin.com/in/mohammed-qahtani-08b90931; X/IG @qahtani_speaks; YouTube @qahtani_speaks", followers="n/a",
         selling="Yes (keynotes, 500+ workshops, coaching)", activity="rare/moderate",
         why_fit="The single most credentialed Arabic public-speaking expert alive; instant authority story (stutter→world champ) made for a VSL", depth=10,
         sources="https://www.qahtanispeaks.com/ ; https://mediacenter.toastmasters.org/2015-08-17-Saudi-Arabian-engineer-wins-Toastmasters-2015-World-Championship-of-Public-Speaking ; https://en.wikipedia.org/wiki/Mohammed_Qahtani", status=""),
    dict(name="ياسر بن بدر الحزيمي / Yasser Al-Huzaimi (speaking angle)", category="Speaking",
         expertise="الإلقاء والتأثير + خطابة; author of المتحدث البارع (2002, still a category-standard book)",
         credentials="20+ yrs; BA Arabic (KSU), Higher Diploma family counseling (KFU); TVTC-certified course + Speakers International cert",
         role="Independent Saudi trainer/author", socials="n/a", followers="n/a",
         selling="Yes (paid دورة المتحدث البارع, filmed-rep training format)", activity="rare (podcast/radio guest)",
         why_fit="Deep craft-first methodology (3 filmed reps per trainee + critique), zero funnel sophistication — classic NH raw material",
         depth=9, sources="https://www.goodreads.com/book/show/8082350 ; https://groups.google.com/g/almada/c/3VDGxgYgoQU",
         status="Cross-listed: also found by Leadership scout (same person, different angle)"),
    dict(name="د. عبدالله البابطين / Dr. Abdullah Al-Babtain", category="Speaking",
         expertise="فن الإلقاء والمواجهة والخطابة (runs the Kingdom's first specialized إلقاء center, est. 1999)",
         credentials="25+ yrs; MA advanced management; 140+ programs delivered, 22 international courses across 8 countries; center: 72,000 trainees, 672 courses",
         role="Director & lead trainer, مركز الإلقاء للتدريب, Riyadh",
         socials="X/IG @alelqatraining (center, ~2,300 IG followers, 1,164 posts)", followers="IG ~2.3k (center)",
         selling="Yes (B2C cohort courses men/women/kids)", activity="active (center accounts)",
         why_fit="25-yr institutional moat in exactly our niche, tiny digital footprint vs. depth — textbook undervalued expert", depth=9,
         sources="https://alelqa.com/ ; http://el.sa/ ; https://x.com/alelqatraining", status=""),
    dict(name="حاتم عابد الرحيلي / Hatem Al-Rehaili", category="Speaking",
         expertise="الظهور الإعلامي + executive media training, crisis communication, message building",
         credentials="~15 yrs; MA Journalism (Imam Univ., honors); 15,000+ trainees local+regional; 10 books; 4 trainer certifications (TVTC etc.); ex-Okaz/Al-Watan/Al-Eqtisadiah journalist",
         role="Independent trainer/consultant to gov, private & nonprofit sectors, Madinah",
         socials="LinkedIn linkedin.com/in/حاتم-عابد-الرحيلي-33189a105; @hatem_alrehili (variants)", followers="n/a",
         selling="Yes (courses incl. الظهور الإعلامي للقيادات العليا/CEOs)", activity="rare",
         why_fit="Executive media-presence is literally the survey's #1 desire; he already sells it to leaders but has no funnel/content machine", depth=8,
         sources="https://www.rihaili.com/عن-حاتم/ ; https://www.rihaili.com/courses/1246/", status=""),
    dict(name="ممدوح الشلال / Mamdouh Al-Shalal", category="Speaking",
         expertise="فن الإلقاء والتأثير; author of فن الإلقاء المميز (Jarir-stocked)",
         credentials="18 yrs training; TEDx speaker; TV/radio appearances; founder of Tofaaq Academy",
         role="Founder, أكاديمية توفاق; Saudi (Eastern Province — chamber courses in Hafr Al-Batin)",
         socials="X @mamdohalshalal; YouTube channel", followers="n/a",
         selling="Yes (paid دورة فن الإلقاء والتأثير via own academy)", activity="active-ish (X, YouTube, podcast guest — بودكاست أروقة)",
         why_fit="Book + own academy + 18 yrs = productizable expert already half-way to an offer, needs acquisition machine", depth=8,
         sources="https://manhom.com/شخصيات/ممدوح-الشلال/ ; https://tofaaq.com/course/دورة-فن-الإلقاء-والتأثير/ ; https://www.spa.gov.sa/w615735", status=""),
    dict(name="عادل بارباع / Adel Barbaa", category="Speaking",
         expertise="Voice, vocal delivery & التعليق الصوتي / broadcaster-making (صناعة المذيع)",
         credentials="30+ yrs; voice of Saudia Airlines' travel dua; Monte Carlo Intl radio, Al Jazeera Training, Egypt Media Production City; TVTC-certified; training since 2005",
         role="News anchor Alif Alif FM + voice trainer (1stc.sa, almentor)",
         socials="TikTok @adel.baraba", followers="n/a", selling="Yes (paid voice-skills courses, almentor courses)",
         activity="active (TikTok/Snap presence)",
         why_fit="Iconic voice every Saudi has heard on a plane; unique \"voice = executive presence\" angle nobody has productized", depth=8,
         sources="https://www.almentor.net/mentors/Adel-Barbaa ; https://1stc.sa/trainer/15 ; https://www.almrsal.com/post/965904", status=""),
    dict(name="د. محمد العامري / Dr. Mohammed Al-Ameri", category="Speaking",
         expertise="Presentation & delivery skills within leadership/management psychology",
         credentials="30+ yrs; PhD admin psychology; TVTC-certified; trained Saudi Royal Court staff; runs flagship 5-day Presentation Skills course",
         role="Consultant/trainer, شركة الإتقان الدولي للاستشارات",
         socials="LinkedIn linkedin.com/in/mohammedaameri; X @MOHAMMEDAAMERI; YouTube UCkyidj534lmoHx3MH01RXiQ / sst5channel",
         followers="n/a", selling="Yes (corporate + open-enrollment courses)", activity="very active (site, X, YouTube)",
         why_fit="Royal-Court-level trust signal + 30 yrs; broader than pure إلقاء but sellable as executive-communication authority. Also surfaced independently in the career-verticals (PMP) sweep as an already-large multi-platform creator — partner-tier, not build-from-zero.", depth=8,
         sources="https://www.mohammedaameri.com/course/22 ; https://x.com/MOHAMMEDAAMERI ; https://mohammedaameri.com/blog/122",
         status="Cross-listed: also found by Career-Verticals scout (PMP angle)"),
    dict(name="د. سالم عريجة / Dr. Salem Areja", category="Speaking",
         expertise="الظهور الإعلامي for government leaders; academic media communication",
         credentials="Senior faculty; PhD, Media Dept faculty member, Umm Al-Qura University; delivers exec media-appearance programs to TVTC leadership",
         role="Faculty, Dept. of Media, UQU, Makkah", socials="n/a", followers="n/a",
         selling="Partially (institutional training gigs, no D2C)", activity="none",
         why_fit="Pure hidden expert: university depth + gov-leader clientele, zero social — exactly the profile NH manufactures into a creator", depth=8,
         sources="https://uqu.edu.sa/App/News/97959", status=""),
    dict(name="طراد باسنبل / Trad Basonbul", category="Speaking",
         expertise="فن الخطابة والإلقاء + on-air presenting craft",
         credentials="~15 yrs media; MixFM radio presenter, TEDx speaker, conference MC; personal-development consultant",
         role="Presenter MixFM Saudi; founder trad.academy",
         socials="IG @trad_b; YouTube (site)", followers="n/a",
         selling="Yes (SAR 500–2,000 خطابة course on own academy + عصارة platform)", activity="active (radio + IG)",
         why_fit="Already monetizing an إلقاء course with real broadcast craft; needs offer/funnel upgrade more than audience", depth=6,
         sources="https://trad.academy/ ; https://osarh.com/courses/51/دورة-فن-الخطابة-والالقاء ; https://www.instagram.com/trad_b/", status=""),
    dict(name="عادل الجهيمان / Adel Al-Johaimani", category="Speaking",
         expertise="Arabic competitive speechcraft (خطابة عربية)",
         credentials="1st place, Arabic Speech Contest, Saudi Annual Toastmasters Conference (SATAC), Jeddah 2024",
         role="n/a", socials="n/a", followers="n/a", selling="No", activity="none",
         why_fit="Kingdom-level Arabic speech champion with zero footprint — the \"pure expert, no social\" gold NH wants", depth=7,
         sources="https://al-hadath.com/post/73360", status="Contact fields n/a — session search budget exhausted, needs LinkedIn/X follow-up"),
    dict(name="عبدالله المغرور / Abdullah Al-Mughror", category="Speaking",
         expertise="Arabic impromptu speaking + speech evaluation (rarest coaching skill)",
         credentials="Triple winner SATAC 2024: 1st Impromptu, 1st Evaluation, 3rd Arabic Speech",
         role="n/a", socials="n/a", followers="n/a", selling="No", activity="none",
         why_fit="Most-decorated competitor at Saudi nationals; evaluation champions make the best coaches", depth=7,
         sources="https://al-hadath.com/post/73360", status="Contact fields n/a — needs LinkedIn/X follow-up"),
    dict(name="حسن البيتي / Hassan Al-Baiti", category="Speaking",
         expertise="Arabic competitive speechcraft",
         credentials="2nd place Arabic Speech Contest, SATAC 2024 Jeddah",
         role="n/a", socials="n/a", followers="n/a", selling="No", activity="none",
         why_fit="Same hidden-champion pool; bench candidate", depth=6,
         sources="https://al-hadath.com/post/73360", status="Contact fields n/a — needs LinkedIn/X follow-up"),
    dict(name="خديجة الصائغ / Khadija Al-Saigh", category="Speaking",
         expertise="Arabic impromptu + evaluation (female)",
         credentials="2nd Impromptu + 2nd Evaluation, SATAC 2024",
         role="n/a", socials="n/a", followers="n/a", selling="No", activity="none",
         why_fit="Female speech champion — female Saudi-employee segment coverage where supply is near-zero", depth=6,
         sources="https://al-hadath.com/post/73360", status="Contact fields n/a — needs LinkedIn/X follow-up"),
    dict(name="د. محمد بن صالح الكثيري / Dr. Mohammed Al-Kathiri", category="Speaking",
         expertise="مهارات الإلقاء والعرض (university continuing-ed)",
         credentials="PhD; lead trainer of IAU's paid الإلقاء والعرض course",
         role="Trainer, Imam Abdulrahman bin Faisal University (Dammam) continuing education",
         socials="n/a", followers="n/a", selling="Via university (paid course)", activity="none",
         why_fit="University-backed إلقاء trainer in Eastern Province, no personal brand — manufacturable", depth=6,
         sources="https://sf.iau.edu.sa/courses/8/مهارات-الإلقاء-والعرض", status=""),
    dict(name="شمائل بنت يوسف العبود / Shamail Al-Aboud", category="Speaking",
         expertise="مهارات الإلقاء والعرض (female trainer)",
         credentials="Co-trainer IAU الإلقاء والعرض course",
         role="Trainer, IAU continuing education, Dammam",
         socials="n/a", followers="n/a", selling="Via university", activity="none",
         why_fit="One of very few institutionally-vetted female إلقاء trainers found", depth=6,
         sources="https://sf.iau.edu.sa/courses/8/مهارات-الإلقاء-والعرض", status=""),
    dict(name="منال الخطيب / Manal Al-Khatib", category="Speaking",
         expertise="فن الخطابة والإلقاء (online, Arabic)",
         credentials="Certified trainer; accreditations from Dubai Media Inc., Mohammed bin Rashid Educational Foundation, Focus Academy",
         role="Trainer on Kun Academy + Focus Academy",
         socials="n/a", followers="n/a", selling="Yes (paid online إلقاء courses)", activity="active (course platforms)",
         why_fit="Proven Arabic online-course seller in our exact niche; verify Saudi-market focus before outreach", depth=6,
         sources="https://kun.academy/trainer-view/298 ; https://focusacademy.tv/expert-view/99/منال-الخطيب",
         status="Borderline: Gulf-wide, Dubai-accredited, Saudi base unverified"),
    dict(name="Kevin Abdulrahman", category="Speaking",
         expertise="CEO public-speaking & executive-presence coaching",
         credentials="20+ yrs claimed; coach to CEOs, ministers, royalty; dedicated Riyadh/Saudi practice pages",
         role="Principal, Executive Authority", socials="n/a", followers="n/a",
         selling="Yes (high-ticket advisory)", activity="active (SEO content)",
         why_fit="Proof the Saudi exec-presence market pays premium; not Arabic — competitive intel more than signing target", depth=5,
         sources="https://kevinabdulrahman.org/services/media-training/public-speaking-coach-riyadh/",
         status="Borderline: English-only, expat serving Saudi — competitive intel, not a signing target"),

    # ---------------- CAREER-VERTICAL (raw: 27) ----------------
    dict(name="عمر حماد / Omar Hammad", category="Career-Vertical (Nursing)",
         expertise="Nursing careers (SNLE/Prometric)",
         credentials="13+ yrs Prometric training; BSN Univ. of Jordan 2004; ex-clinical trainer Univ. of Jordan + Al-Mowasat institutes (Khobar)",
         role="Founder, Training4Nurses Academy", socials="n/a",
         followers="n/a", selling="Yes — SNLE/Prometric courses at 99–150 SAR, 700+ Qs, mock exams", activity="active (course platform)",
         why_fit="Proven demand + already selling but tiny distribution; NH ads could 100x him", depth=8,
         sources="https://training4nurses-academy-2019.teachable.com/", status="Flag: Jordanian serving KSA/Oman/Qatar in Arabic"),
    dict(name="عبدالله الحارثي / Abdullah Alharthi", category="Career-Vertical (Nursing)",
         expertise="Nursing careers", credentials="Licensed Saudi nurse who passed SNLE",
         role="n/a", socials="X/Rattibha @Alharthi", followers="n/a",
         selling="Nothing — shared free experience thread", activity="rare",
         why_fit="Clearly-Saudi nurse voice in a vertical dominated by Egyptian/Jordanian trainers — whitespace", depth=5,
         sources="https://rattibha.com/thread/1565677685833142273", status=""),
    dict(name="SNLE_NURSE (name n/a)", category="Career-Vertical (Nursing)",
         expertise="Nursing careers", credentials="n/a", role="n/a",
         socials="X @SNLE_NURSE", followers="n/a",
         selling="Posts SNLE lessons + exam compilations (تجميعات)", activity="active",
         why_fit="Anonymous but already owns SNLE keyword on X; unmask + sign", depth=5,
         sources="DDG results via https://snlepass.com context search", status="Anonymous — identity unverified"),
    dict(name="Mohamed Galal / محمد جلال", category="Career-Vertical (Nursing)",
         expertise="Nursing careers", credentials="n/a", role="n/a", socials="n/a", followers="n/a",
         selling="n/a", activity="active",
         why_fit="High-volume Prometric question content (YouTube \"أكثر 100 سؤال تكراراً في برومترك التمريض\")", depth=4,
         sources="https://www.youtube.com/watch?v=B1gvvrRFtEw", status="Flag: likely Egyptian"),
    dict(name="سعيد محمد شحادة / Saeed Mohammed Shehadeh", category="Career-Vertical (Nursing)",
         expertise="Nursing careers", credentials="n/a", role="n/a",
         socials="YouTube channel", followers="n/a", selling="n/a", activity="active",
         why_fit="Dedicated nursing-subject explainer channel", depth=4,
         sources="https://www.youtube.com/channel/UCHArGzEN_s5Hakj6Mp1VLeg", status="Nationality n/a (likely Egyptian)"),
    dict(name="د. وفاء السالم / Dr. Wafaa Al-Salem", category="Career-Vertical (Medical)",
         expertise="Medical careers (SMLE)",
         credentials="OBGYN physician; flagship 5-day OBGYN SMLE review, question-based teaching praised by students",
         role="SMLE instructor @ Virtual Medical Academy", socials="X @WafaS10", followers="n/a",
         selling="Yes — paid SMLE OBGYN course via VMA", activity="active (X + recurring course runs)",
         why_fit="The named star instructor of the biggest SMLE course brand; exact \"expert with no own funnel\" profile — top pick of this vertical", depth=9,
         sources="https://blog.medicalacademy.org/دورات-اختبار-هيئة-التخصصات-الصحية-smle/ ; https://x.com/WafaS10", status=""),
    dict(name="د. جمال عمر / Dr. Jamal Omar", category="Career-Vertical (Medical)",
         expertise="Medical careers (SMLE)", credentials="Pediatrician; 4-day interactive MCQ-based SMLE pediatrics course",
         role="SMLE instructor @ VMA", socials="n/a", followers="n/a",
         selling="Yes — paid course via VMA", activity="rare (no own channels found)",
         why_fit="Proven paid instructor, zero personal brand = NH builds it", depth=8,
         sources="https://blog.medicalacademy.org/دورات-اختبار-هيئة-التخصصات-الصحية-smle/", status=""),
    dict(name="د. عبدالله ثوابة / Dr. Abdullah Thawabah", category="Career-Vertical (Medical)",
         expertise="Medical careers (SMLE)", credentials="General surgeon; co-teaches SMLE surgery course",
         role="SMLE instructor @ VMA", socials="n/a", followers="n/a",
         selling="Yes — via VMA", activity="rare",
         why_fit="Same VMA-poach play", depth=7,
         sources="https://blog.medicalacademy.org/دورات-اختبار-هيئة-التخصصات-الصحية-smle/", status=""),
    dict(name="د. عبدالله محفوظ / Dr. Abdullah Mahfouz", category="Career-Vertical (Medical)",
         expertise="Medical careers (SMLE)", credentials="General surgeon; co-teaches SMLE surgery course",
         role="SMLE instructor @ VMA", socials="n/a", followers="n/a",
         selling="Yes — via VMA", activity="rare",
         why_fit="Same VMA-poach play", depth=7,
         sources="https://blog.medicalacademy.org/دورات-اختبار-هيئة-التخصصات-الصحية-smle/", status=""),
    dict(name="د. عبدالله البيروتي / Dr. Abdullah Albeirutty", category="Career-Vertical (Medical)",
         expertise="Medical careers (SMLE/resources)", credentials="Saudi physician; curates SMLE MCQ/Telegram resource lists",
         role="n/a", socials="X @aalbeirutty", followers="n/a",
         selling="Nothing visible — free resource threads", activity="active on X",
         why_fit="Saudi doctor already trusted as SMLE-resource curator, not monetized", depth=7,
         sources="https://x.com/aalbeirutty/status/1783080438405181480", status=""),
    dict(name="أفنان حكمي / Afnan Hakami", category="Career-Vertical (Pharmacy)",
         expertise="Pharmacy careers (SPLE)",
         credentials="Saudi hospital pharmacist (controlled-substances custodian across Saudi hospitals); long-running professional blog incl. SPLE guide",
         role="Hospital pharmacist", socials="n/a", followers="n/a",
         selling="Nothing — free blog", activity="rare",
         why_fit="Deep Saudi practitioner + teaching instinct, zero productization", depth=6,
         sources="https://phafnanhakami.wordpress.com/", status=""),
    dict(name="أبرار خالد ثابت / Abrar Khaled Thabit", category="Career-Vertical (Pharmacy)",
         expertise="Pharmacy careers (SPLE)", credentials="Pharmacist; wrote detailed SPLE explainer (2020) on her pharmacy blog",
         role="n/a", socials="X @abrarthabit", followers="n/a",
         selling="Nothing — free blog", activity="rare",
         why_fit="Same profile as Hakami; SPLE whitespace", depth=5,
         sources="https://athabit.wordpress.com/2020/09/21/...sple/ ; https://twitter.com/abrarthabit", status=""),
    dict(name="ريان السعدي / Rayan Al-Saadi", category="Career-Vertical (Pharmacy)",
         expertise="Pharmacy careers (SPLE)", credentials="Pharmacist; authored viral SPLE how-to thread",
         role="n/a", socials="thread on rattibha.com", followers="n/a",
         selling="Nothing", activity="rare",
         why_fit="Saudi SPLE voice with proven engagement", depth=5,
         sources="https://rattibha.com/thread/1350462930463109124", status=""),
    dict(name="سمر الحجوري / Samar Alhojori", category="Career-Vertical (Accounting)",
         expertise="Accounting careers (SOCPA زمالة)",
         credentials="SOCPA fellowship holder (2021); ex-Big 4; 4-yr documented zamalah journey; runs study-resource blog + Telegram",
         role="Accountant", socials="X @S333SH; blog samaralhojori.com; Telegram t.me/Accountants3", followers="n/a",
         selling="No — free mentoring/resources only", activity="active (blog + Telegram)",
         why_fit="THE organic SOCPA authority with zero monetization — cleanest signing in the sweep; top pick of this vertical", depth=8,
         sources="https://samaralhojori.com/2021/09/14/socpa-3/ ; https://t.me/s/Accountants3", status=""),
    dict(name="د. مصعب الجعيد / Dr. Mosaab Aljuaid", category="Career-Vertical (Accounting)",
         expertise="Accounting careers (SOCPA)",
         credentials="PhD; Executive Director of Membership & Professional Qualification at SOCPA; runs exam-prep group w/ per-subject question banks (286 Qs financial acct.)",
         role="SOCPA executive", socials="X @MosaabAljuaid + group @SOCPA_SA", followers="n/a",
         selling="Free official question banks", activity="active on X",
         why_fit="Regulator insider, likely un-signable — but his group proves audience demand", depth=6,
         sources="https://x.com/MosaabAljuaid ; https://twitter.com/socpa_sa", status="Flag: regulator insider, likely un-signable"),
    dict(name="دلال المرداس / Dalal Al-Mirdas", category="Career-Vertical (Accounting)",
         expertise="Accounting careers (SOCPA)", credentials="SOCPA fellowship passer; published experience write-up",
         role="n/a", socials="n/a", followers="n/a", selling="Nothing", activity="rare",
         why_fit="Pool of Saudi zamalah passers to screen as creators (also seen in same source: عبدالله الحصيني, عبدالمحسن الزبن)", depth=4,
         sources="https://samaralhojori.com/2021/03/27/3-socpa/", status=""),
    dict(name="م. دخيل الدخيل / Eng. Dakheel Al-Dakheel", category="Career-Vertical (Engineering)",
         expertise="Engineering careers (Aramco)",
         credentials="Aramco employee, KFUPM grad; podcast episodes on \"how to get hired at Aramco\" + career-path clarity",
         role="Aramco", socials="TikTok @mukhtalif_career (featured)", followers="n/a",
         selling="Nothing own", activity="rare (guest appearances)",
         why_fit="\"Get into Aramco\" is the highest-desire engineering topic in KSA; no one owns it", depth=6,
         sources="Petroly Podcast YouTube \"كيف أتوظف في أرامكو مع م. دخيل الدخيل\"", status=""),
    dict(name="اختبار FE للمهندسين (name n/a)", category="Career-Vertical (Engineering)",
         expertise="Engineering careers (SCE/FE accreditation)", credentials="n/a", role="n/a",
         socials="X @FE_exam100", followers="n/a", selling="FE prep content", activity="active",
         why_fit="Anonymous account already owning FE-exam keyword; unmask + sign or replicate", depth=5,
         sources="https://twitter.com/fe_exam100", status="Anonymous — identity unverified"),
    dict(name="Ahmed Sultan / أحمد سلطان", category="Career-Vertical (Cybersecurity)",
         expertise="Cybersecurity careers",
         credentials="Veteran Arabic networking/security instructor; Security+ SY0-701 courses, labs",
         role="Founder/instructor, Netriders Academy", socials="X @ahmedesultan", followers="n/a",
         selling="Yes — paid cert courses", activity="active",
         why_fit="Already scaled — benchmark/partner rather than raw signing", depth=7,
         sources="https://netriders.academy/", status="Flag: Egyptian, already scaled"),
    dict(name="Omar Shaaban / عمر شعبان", category="Career-Vertical (Data)",
         expertise="Data careers", credentials="Data-analysis instructor, channel \"مدرسة تحليل البيانات\"",
         role="n/a", socials="IG @Omar.shaaban88; YouTube مدرسة تحليل البيانات", followers="n/a",
         selling="n/a", activity="active",
         why_fit="Arabic data-career teaching; Saudi-focused positioning possible", depth=5,
         sources="DDG result (YouTube channel مدرسة تحليل البيانات)", status="Nationality n/a, likely Egyptian"),
    dict(name="هشام المنصور / Hesham Al-Mansoor", category="Career-Vertical (PM)",
         expertise="Project management careers (PMP)",
         credentials="PMI-certified PMP trainer; trained 14,000+ employees across Saudi gov + corporates; own academy (بصمة التغيير)",
         role="Founder, Bassma Change Academy", socials="LinkedIn sa.linkedin.com/in/hesham-almansoor; YouTube channel", followers="n/a",
         selling="Yes — PMP courses + consulting", activity="active (site + LinkedIn)",
         why_fit="Massive B2B credibility, weak consumer funnel — exactly what NH industrializes; top pick of this vertical", depth=8,
         sources="https://bassmh-sa.com/pmp/", status=""),
    dict(name="Sayed Mohsen / سيد محسن", category="Career-Vertical (PM)",
         expertise="Project management careers",
         credentials="PfMP, PgMP, PMP, RMP, SP, ACP, PBA, PMOCP, P3O instructor",
         role="Independent PM instructor", socials="X @SayedMohsenPMP; YouTube \"SAYED MOHSEN PMP\"", followers="n/a",
         selling="Yes — PMP training", activity="active",
         why_fit="Stacked credentials", depth=7,
         sources="X @SayedMohsenPMP (via DDG)", status="Flag: likely Egyptian serving KSA"),
    dict(name="بندر السحيمي / Bandar Al-Suhaimi", category="Career-Vertical (Procurement)",
         expertise="Procurement/gov-tenders careers",
         credentials="Trainer on نظام المنافسات والمشتريات الحكومية; launched own knowledge platform; tracks 1448H regulation amendments",
         role="Independent procurement trainer/consultant", socials="LinkedIn linkedin.com/posts/bandar-alsuhimi", followers="n/a",
         selling="Yes — webinars + knowledge platform", activity="active on LinkedIn",
         why_fit="Flagged-whitespace vertical (Etimad/tenders) and he's the only named individual in it", depth=7,
         sources="LinkedIn webinar \"نظرة عامة على نظام المنافسات والمشتريات الحكومية\"", status=""),
    dict(name="غفران محمد لقور / Ghufran Laqour", category="Career-Vertical (Legal)",
         expertise="Legal careers (محاماة)",
         credentials="Licensed lawyer + certified trainer; BA Sharia; heads legal committee (Taif volunteer team); course \"مهارات المحامي الناجح\"",
         role="Lawyer/trainer", socials="n/a", followers="n/a",
         selling="Yes — course on Waqf LMS", activity="rare",
         why_fit="Only named individual found teaching lawyer skills; legal vertical otherwise institutional", depth=5,
         sources="https://lms.waqf.org.sa (course listing via DDG)", status=""),
    dict(name="باسل الحجيري / Basel Al-Hujairi", category="Career-Vertical (Banking)",
         expertise="Banking careers (CME-1)", credentials="Passed CME-1; authored widely-shared prep thread (legislations + operations parts)",
         role="Finance professional", socials="thread on rattibha.com", followers="n/a",
         selling="Nothing — free thread", activity="rare",
         why_fit="CME-1 is mandatory for every CMA-registered person; zero creators own it", depth=5,
         sources="https://rattibha.com/thread/1489478797783142401", status=""),
    dict(name="محمد السيد / Muhammad Al-Sayed", category="Career-Vertical (Banking)",
         expertise="Banking careers (CME-1)", credentials="CME-1 session speaker on Doroob (HRDF platform)",
         role="n/a", socials="n/a", followers="n/a",
         selling="Teaches via Doroob (free national platform)", activity="rare",
         why_fit="Only named CME-1 instructor found", depth=4,
         sources="https://lms.doroob.sa/courses/course-v1:Doroob+W.S-FINAN007+SEP2021/about", status="Nationality n/a"),

    # ---------------- AI FOR PROFESSIONALS (raw: 15) ----------------
    dict(name="د. مازن مليباري / Dr. Mazen Melibari", category="AI for Professionals",
         expertise="Practical AI implementation, AI tools education (Krea, ChatGPT, Claude), AI for business",
         credentials="PhD AI (Univ. of Waterloo); ex-Google Developer Expert ML; ex-Misk Foundation chief AI researcher/advisor; Asst Prof AI Umm Al-Qura Univ; founder DEEP.SA; ~15+ yrs",
         role="CTO & Partner, TAM (Saudi digital transformation co.)",
         socials="X @mznmel", followers="X 86.4K", selling="No paid courses seen (free content + corporate role)", activity="active",
         why_fit="Deepest verifiable Saudi AI credential stack + already teaches tools in Saudi dialect to mass audience, zero TikTok — THE candidate to become the Saudi \"AI at work\" authority", depth=10,
         sources="https://x.com/mznmel/status/1988291763342020810 ; https://jawlah.co/53265", status=""),
    dict(name="د. مجدل القحطاني / Dr. Mejdal Alqahtani", category="AI for Professionals",
         expertise="AI + data science for business/industry; corporate AI training",
         credentials="12+ yrs engineering/AI/DS; 25+ AI solutions delivered; senior data-science trainer local & intl; PhD; board member Saudi Society for Data Science",
         role="Assistant Professor, Industrial Engineering, King Saud University + AI consultant (gov & private)",
         socials="LinkedIn linkedin.com/in/mejdal-alqahtani-18171b42; X @Dr_Mejdal", followers="Named top-20 Saudi LinkedIn influencer by Favikon",
         selling="Yes — paid consulting/training via institutions & Thakaa platform", activity="active",
         why_fit="Exactly the \"AI consultant who trains corporates\" archetype, LinkedIn-first, no TikTok", depth=9,
         sources="https://faculty.ksu.edu.sa/en/node/113623 ; https://thakaa.sa/consultations/contributors/majdal?topic=ai ; https://www.favikon.com/blog/top-linkedin-influencers-saudi-arabia", status=""),
    dict(name="د. ظبية البوعينين / Dr. Dhabiah AlBuainain", category="AI for Professionals",
         expertise="AI for leaders/governance; AI applications in education, healthcare, institutions",
         credentials="PhD Cloud Computing & AI (Glasgow Caledonian, 2018); CAIC certified AI consultant (USAII); assistant professor; founding chair AI Governance Society",
         role="Assistant Professor (Saudi university) + founding board chair, AI Governance Society",
         socials="LinkedIn (active); X @dabuainain", followers="n/a",
         selling="Yes — teaches \"AI for Leaders 2025\" course at Bayan Academy", activity="active",
         why_fit="Saudi woman with real PhD depth already monetizing AI-for-professionals training via academies", depth=8,
         sources="https://x.com/dabuainain/status/1929573460109373860 ; https://academy.bfuture.edu.sa/", status=""),
    dict(name="م. آراء الهمزاني / Eng. Araa Alhamzani", category="AI for Professionals",
         expertise="AI + business intelligence consulting, data governance",
         credentials="MSc Artificial Intelligence; DATA100 2026 (top 100 Saudi data/IT leaders)",
         role="Director, Data Management Office, Federation of Saudi Chambers",
         socials="LinkedIn (ae.linkedin.com); X @araa_saudi", followers="n/a",
         selling="Partially (consulting; employed)", activity="active",
         why_fit="Senior Saudi woman AI leader with national recognition and employee-facing (chambers/business) audience", depth=8,
         sources="https://x.com/araa_saudi ; makkahnewspaper.com (DATA100 2026 coverage)", status=""),
    dict(name="د. غالب بن حمود الشمري / Dr. Ghaleb bin Hammoud Alshammari", category="AI for Professionals",
         expertise="Generative AI and applications training",
         credentials="PhD; founder & chairman, Saudi Society for AI & Intelligent Systems (KSU-based); delivers \"Generative AI and its applications\" courses",
         role="Chairman, Saudi Society for AI & Intelligent Systems / King Saud University",
         socials="n/a", followers="n/a", selling="Institutional training (courses via society)", activity="rare",
         why_fit="Runs the kingdom's AI professional society and personally teaches gen-AI — authority without creator infrastructure; purest NH thesis bet: maximum credibility, zero monetization infrastructure", depth=8,
         sources="https://ksuai.ksu.edu.sa/ar/node/2970", status=""),
    dict(name="د. لطيفة العبدالكريم / Dr. Latifa AlAbdulkarim", category="AI for Professionals",
         expertise="AI & law, AI governance, national AI policy",
         credentials="PhD CS-AI (Liverpool, 2017); Asst Prof KSU; global \"100 Brilliant Women in AI Ethics\"-tier recognition; World Government Summit speaker",
         role="Shura Council member + Assistant Professor, King Saud University",
         socials="Active X presence (handle n/a)", followers="n/a", selling="No", activity="active (speaking/media)",
         why_fit="Highest-authority Saudi AI woman; likely NOT signable (Shura member)", depth=9,
         sources="https://saudipedia.com/en/latifa-mohammed-al-abdulkarim ; https://www.worldgovernmentssummit.org/ar/media-hub/speakers/detail/636850891825202384-latifa-alabdulkarim",
         status="Flag: likely un-signable — Shura Council member, aspirational/advisor tier"),
    dict(name="عبدالرحمن الدعيج / Abdulrahman Aldaej", category="AI for Professionals",
         expertise="Data & AI security; enterprise AI",
         credentials="Senior corporate AI/data leader at IBM; ranked #15 Saudi LinkedIn influencer 2026 (Favikon 94.7/100)",
         role="Data & AI Security Leader, IBM (Saudi Arabia)",
         socials="LinkedIn (via Favikon)", followers="Top-20 Saudi LinkedIn influencer", selling="No", activity="active (LinkedIn)",
         why_fit="Big-tech Saudi AI leader archetype who already posts — \"senior AI leader who trains on the side\" target", depth=8,
         sources="https://www.favikon.com/blog/top-linkedin-influencers-saudi-arabia", status=""),
    dict(name="هاني نواية / Hani Nawaya", category="AI for Professionals",
         expertise="AI-powered data analysis for employees (Excel, Power BI, SQL, ChatGPT, automation)",
         credentials="Trainer & consultant in AI + data analysis; runs own training platform (Nawaedu \"Data Analysis Diploma\") + tech co (Nawahtech)",
         role="Founder/trainer, Nawaedu & Nawahtech",
         socials="X @HaniNawaya", followers="n/a", selling="Yes — already sells own diploma", activity="active",
         why_fit="Purest \"make employees more valuable with AI\" curriculum already live", depth=6,
         sources="https://x.com/haninawaya ; nawaedu.com", status="Nationality/base unverified — verify Saudi focus"),
    dict(name="سامي المحيميد / Sami Almuhaimeed", category="AI for Professionals",
         expertise="AI agents & AI for business operations; building \"Saudi Legal AI Framework\"",
         credentials="Business development & operational-efficiency consultant; deep hands-on AI-agent experimentation (Claude Code, multi-agent systems)",
         role="Independent consultant", socials="X @SamiBizConsult", followers="n/a", selling="Consulting (no courses seen)", activity="active",
         why_fit="Saudi consultant already producing sophisticated Arabic AI-agent content for business audience", depth=5,
         sources="https://x.com/SamiBizConsult/status/2079552659942420928", status=""),
    dict(name="م. عارف سمان / Eng. Arif Samman", category="AI for Professionals",
         expertise="Prompt engineering & AI literacy education in Arabic",
         credentials="Engineer/consultant (\"المستشار م.\"); writes structured Arabic educational threads on prompt engineering",
         role="Independent consultant", socials="X @arifsamman", followers="n/a", selling="n/a", activity="active",
         why_fit="Teaches the exact SAMAI-wave skill (prompts) in Arabic", depth=5,
         sources="https://x.com/arifsamman/status/1818679756428034455", status="Nationality likely Saudi (Hijazi) — verify"),
    dict(name="د. أماني بنت خلف سمه / Dr. Amani Samha", category="AI for Professionals",
         expertise="AI & intelligent systems (academic)",
         credentials="PhD; co-founder & vice-chair, Saudi Society for AI & Intelligent Systems",
         role="Vice Chairman, Saudi Society for AI & Intelligent Systems (KSU)",
         socials="n/a", followers="n/a", selling="No", activity="rare",
         why_fit="Co-founder of national AI society; credible female academic authority, unmonetized", depth=7,
         sources="https://ksuai.ksu.edu.sa/ar/node/2970", status=""),
    dict(name="أ.د. أحمد بن إبراهيم الزهراني / Prof. Ahmad bin Ibrahim Alzahrani", category="AI for Professionals",
         expertise="AI & intelligent systems (academic)",
         credentials="Full professor; founding board member, Saudi Society for AI & Intelligent Systems",
         role="Professor, King Saud University", socials="n/a", followers="n/a", selling="No", activity="none/rare",
         why_fit="Full-professor depth, zero content — pure-expert signing per NH thesis", depth=7,
         sources="https://ksuai.ksu.edu.sa/ar/node/2970", status=""),
    dict(name="د. أماني العقالي / Dr. Amani Al-Aqali", category="AI for Professionals",
         expertise="AI policies in education; AI for educators/employees in gov sector",
         credentials="PhD in AI policies (Imam Mohammad Ibn Saud Islamic Univ.)",
         role="Ministry of Education, Saudi Arabia", socials="LinkedIn sa.linkedin.com/in/د-أماني-العقالي-", followers="n/a",
         selling="No", activity="rare (LinkedIn)",
         why_fit="Gov-sector AI-adoption angle for Saudi employees (education = biggest employer)", depth=6,
         sources="https://sa.linkedin.com/in/د-أماني-العقالي-", status=""),
    dict(name="علي السهلي / Ali Alsahli", category="AI for Professionals",
         expertise="AI training bundled with self-development/e-training",
         credentials="Certified trainer (مدرب معتمد); multi-domain (family consulting, self-dev, e-training, AI)",
         role="Independent certified trainer, Saudi Arabia", socials="X @alsahli_ali", followers="n/a",
         selling="Likely (paid training)", activity="active",
         why_fit="Saudi trainer already selling to consumer audience — but AI depth shallow (generalist)", depth=3,
         sources="https://x.com/alsahli_ali", status=""),
    dict(name="فالح المحمدي / Falah Almohammadi", category="AI for Professionals",
         expertise="AI & societal/economic development commentary",
         credentials="Consultant (unspecified field) writing long-form Arabic AI-opportunity content",
         role="Independent consultant, Saudi Arabia", socials="X @falmohmd", followers="n/a",
         selling="n/a", activity="active",
         why_fit="Saudi consultant voice on AI opportunity; depth unverified — bottom-of-funnel lead only", depth=3,
         sources="https://x.com/falmohmd/status/1991528295817474422", status=""),
]

# Explicit "excluded during research" entries — kept for transparency (namesake
# traps and disqualified leads the scouts explicitly ruled out before scoring).
EXCLUDED = [
    dict(name="د. وفاء سبيتي (ثراء بودكاست)", category="Finance", reason="Kuwait-based AUK professor, not Saudi — namesake trap"),
    dict(name="منصور الدرعي", category="Finance", reason="UAE-based"),
    dict(name="محمد أبو النجا", category="Finance", reason="Egypt-based"),
    dict(name="مريم الخواجه", category="Finance", reason="Self-dev/money-mindset content, no finance credentials"),
    dict(name="خبير اسهم @khabeer999", category="Finance", reason="Stock-tip vibe, not an educator"),
    dict(name="حسام الدين حسن", category="AI for Professionals", reason="Egyptian AI podcast host"),
    dict(name="د. حسين العمري", category="AI for Professionals", reason="Silicon Valley based, nationality unclear"),
    dict(name="مروان GPT", category="AI for Professionals", reason="Yemeni/Egyptian market"),
    dict(name="فيصل السيف", category="AI for Professionals", reason="Mega tech reviewer, not an AI expert — unsignable"),
    dict(name="عبدالله السبيعي", category="AI for Professionals", reason="Phone-tips creator, no AI depth"),
    dict(name="Tareq Amin / Deemah AlYahya", category="AI for Professionals", reason="Sitting executives — unsignable"),
    dict(name="Government-jobs (جدارات) coach", category="Career-Vertical", reason="No credible named individual surfaced, only hashtags/platforms"),
    dict(name="HSE/NEBOSH Arabic star trainer", category="Career-Vertical", reason="Institutes only (ITTI, STTC, IBS), no named star trainer surfaced"),
    dict(name="SCFHS-classification (Mumaris+) consultant", category="Career-Vertical", reason="Service companies only (tasdiq.org), no named individual"),
]

TOP_PICKS = [
    # (name substring to match in CANDIDATES, category label for grouping, rank note)
    ("د. عبدالرحمن بن إبراهيم الدايل", "Leadership", "#1 — complete package: Saudi PhD leadership, Marshall Goldsmith-certified, 26 yrs, 22.7k coached; surfaced independently in 2 scouts"),
    ("د. محمد الخالدي", "Leadership", "#2 — survey-named, verified real: 225k trainees + own academy"),
    ("د. إبراهيم بن حمد القعيد", "Leadership", "#3 — 40-yr legend, العادات العشر author, totally un-productized digitally"),
    ("هدى الغصون", "Leadership", "#4 — ex-Aramco HR chief, unmatched authority for \"get promoted\" ICP"),
    ("ريم بن صديق", "Leadership", "#5 — survey-named, verified ILM leadership trainer, 79.5K X followers"),
    ("مطلق المريشد", "Hidden Experts", "#1 — 40-yr exec authority, millions of فنجان listens, zero personal channels"),
    ("عبدالرحمن الفاضل", "Hidden Experts", "#2 — 40-yr Aramco director, already coach-minded, only an X account"),
    ("عبدالله الجرف", "Hidden Experts", "#4 — ICF PCC + Ministry of HR GM, Thinkers50 nominee, LinkedIn-only"),
    ("نايف الفهيد", "Hidden Experts", "#5 — 25-yr HR director, evergreen فنجان hiring episode, completely invisible otherwise"),
    ("عاصم الرحيلي", "Finance", "#1 — archetype: credentialed, already selling wealth courses, needs acquisition machine"),
    ("خلود الدخيل", "Finance", "#2 — CFA + CEO + female authority, massive untapped creator upside"),
    ("فهد الحويماني", "Finance", "#3 — Jarir-published investing author + TV trust, 30K X, zero funnel"),
    ("ازدهار علاف", "Finance", "#4 — only multi-platform (X/Snap/TikTok) credentialed woman, Snapchat-native"),
    ("د. محمد علي القري", "Finance", "#5 — not a creator, but the halal-compliance co-sign/moat for every finance offer"),
    ("محمد القحطاني", "Speaking", "#1 — crown jewel: only Arab Toastmasters World Champion, made-for-ads origin story"),
    ("ياسر بن بدر الحزيمي", "Speaking", "#2 — 20-25 yr deep-craft veteran, category-defining book, nearly invisible online"),
    ("د. عبدالله البابطين", "Speaking", "#3 — Kingdom's first إلقاء center, 25-yr institutional moat"),
    ("حاتم عابد الرحيلي", "Speaking", "#4 — sells survey's #1 desire (executive الظهور الإعلامي), 15k trainees, 10 books"),
    ("ممدوح الشلال", "Speaking", "#5 — book + own academy + 18 yrs, immediately productizable"),
    ("د. وفاء السالم", "Career-Vertical (Medical)", "Top pick, Medical/SMLE — named star instructor, students praise her by name, renting authority to VMA with no personal funnel"),
    ("سمر الحجوري", "Career-Vertical (Accounting)", "Top pick, Accounting/SOCPA — organic authority, blog+Telegram audience, monetizing nothing"),
    ("هشام المنصور", "Career-Vertical (PM)", "Top pick, PMP — 14,000 trained, Saudi, zero consumer funnel"),
    ("د. مازن مليباري", "AI for Professionals", "#1 — deepest verifiable Saudi AI credential stack, teaches AI tools in Saudi dialect to 86K X followers"),
    ("د. مجدل القحطاني", "AI for Professionals", "#2 — KSU professor + active corporate AI trainer + top-20 Saudi LinkedIn voice"),
    ("د. ظبية البوعينين", "AI for Professionals", "#3 — PhD, already selling \"AI for Leaders\" via academies, founding chair of AI Governance Society"),
    ("م. آراء الهمزاني", "AI for Professionals", "#4 — MSc AI, DATA100, Federation of Saudi Chambers — female-authority play"),
    ("د. غالب بن حمود الشمري", "AI for Professionals", "#5 — chairman of the national AI society, personally teaches gen-AI, near-zero creator presence"),
]

VERTICAL_RANKING = [
    ("1. Medical / SMLE", "Richest vertical — proven paid courses, named star instructors (e.g. د. وفاء السالم) renting authority to a course platform (VMA) with no personal funnels. Move: straight poach."),
    ("2. Accounting / SOCPA زمالة", "Mandatory 6-exam credential, 1,200 SAR/exam, real repeat-failure pain, essentially zero creators. Top pick: سمر الحجوري — organic authority monetizing nothing."),
    ("3. Project Management / PMP", "Biggest paid-training market in KSA (Vision 2030 megaprojects). Top pick: هشام المنصور — 14K trained, Saudi, zero consumer distribution."),
    ("4. Nursing / SNLE (sleeper)", "Largest exam volume, but current expert pool is Jordanian/Egyptian (best available: Omar Hammad). A clearly-Saudi nurse educator would win the niche instantly — recommend an inbound casting funnel rather than more scraping."),
    ("5. Confirmed whitespace, no real competition", "Gov-tenders/Etimad (only Bandar Al-Suhaimi), CME-1 banking prep, legal محاماة — validate willingness-to-pay before building."),
]

HONEST_GAPS = [
    ("Government-jobs (جدارات) coaching", "No credible named individual coach surfaced — only hashtags/platforms."),
    ("HSE/NEBOSH Arabic training", "Institute-dominated (ITTI, STTC, IBS) — no named star trainer surfaced."),
    ("SCFHS-classification (Mumaris+) consulting", "Service companies only (e.g. tasdiq.org) — no named individual found."),
]

METHOD_NOTES = [
    "Sourcing rule (no-fabrication contract): every claim needed a source URL; unknown fields are marked n/a, never guessed. Namesake traps were checked before scoring (e.g. a finance-podcast 'star' who turned out to be a Kuwait-based professor was excluded).",
    "Six parallel research agents ran one per bucket: Leadership, Hidden Experts, Finance, Speaking, Career-Verticals, AI for Professionals — each returned a pipe-delimited raw dataset, quoted below in the 'All Candidates' tab and merged here.",
    "Depth score (1-10): rough proxy for expert-credibility depth as assessed by the sourcing agent, not a validated NH scoring rubric — treat as directional, re-score after your own diligence.",
    "Favikon-sourced entries show an influence score but no public follower counts — counts are marked n/a, not fabricated. Verify LinkedIn URLs individually before outreach.",
    "'Cross-listed' status = the same person was found independently by two different scout agents from two different search angles — treated in the sourcing session as the strongest convergence signal in the dataset.",
    "'DQ' status = the scout explicitly disqualified the candidate for this project (wrong expertise fit or reputational risk) — kept visible here for transparency, excluded from Top Picks.",
    "Nationality flags: several candidates are Saudi-market-relevant but not verified Saudi nationals (Egyptian, Jordanian, Lebanese, Kuwaiti, UAE) — flagged per scout note, not excluded outright except where explicitly disqualified.",
    "IMPORTANT PROVENANCE NOTE: this workbook is a reconstruction. The original working spreadsheet (built live via openpyxl in that session, with full agent-side dedup/scoring performed in a Python script) is not recoverable — only a Slack .txt export of the chat transcript survived. This file reassembles the six agents' raw result payloads exactly as they were reported back into that chat, deduplicated and organized here, but it has not been re-verified against live sources and may not exactly match the original 118-row 'Top Picks: 22' compiled workbook referenced in that session.",
    "Total raw candidates transcribed across all six scouts: {n_raw}. After marking explicit cross-listings and DQs (not deleting rows), distinct signable candidates: {n_distinct}.",
]


def autosize(ws, min_width=10, max_width=60):
    widths = {}
    for row in ws.iter_rows():
        for cell in row:
            if cell.value is None:
                continue
            col = cell.column_letter
            length = len(str(cell.value))
            widths[col] = min(max(widths.get(col, min_width), length + 2), max_width)
    for col, width in widths.items():
        ws.column_dimensions[col].width = width


def style_header(ws, row=1, ncols=1, fill="1F4E78"):
    header_font = Font(name=FONT_NAME, bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill("solid", fgColor=fill)
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(vertical="center", wrap_text=True)


def set_default_font(ws):
    for row in ws.iter_rows():
        for cell in row:
            if cell.font is None or cell.font.name != FONT_NAME:
                existing = cell.font
                cell.font = Font(
                    name=FONT_NAME,
                    bold=existing.bold if existing else False,
                    color=existing.color if existing else None,
                    size=existing.size if existing and existing.size else 10,
                )


def main():
    wb = openpyxl.Workbook()

    # ---------------- All Candidates ----------------
    ws = wb.active
    ws.title = "All Candidates"
    headers = ["Name (AR/EN)", "Category", "Niche / Expertise", "Credentials & Experience",
               "Current Role", "Socials", "Followers", "Selling?", "Online Activity",
               "Why NH Fit", "Depth Score (1-10)", "Status / Flags", "Source URL(s)"]
    ws.append(headers)
    style_header(ws, ncols=len(headers))
    ws.freeze_panes = "A2"

    for c in CANDIDATES:
        ws.append([
            c["name"], c["category"], c["expertise"], c["credentials"], c["role"],
            c["socials"], c["followers"], c["selling"], c["activity"], c["why_fit"],
            c["depth"], c["status"], c["sources"],
        ])

    n_total = len(CANDIDATES)
    n_dq = sum(1 for c in CANDIDATES if c["status"].startswith("DQ"))
    n_crosslisted = sum(1 for c in CANDIDATES if c["status"].startswith("Cross-listed"))

    # thin borders + wrap for readability
    thin = Side(style="thin", color="D9D9D9")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row, max_col=len(headers)):
        for cell in row:
            cell.border = border
            cell.alignment = Alignment(vertical="top", wrap_text=True)
    autosize(ws, max_width=45)

    # ---------------- Top Picks ----------------
    ws2 = wb.create_sheet("Top Picks")
    headers2 = ["Rank Note", "Category", "Name (AR/EN)", "Niche / Expertise", "Why NH Fit",
                "Depth Score", "Socials", "Source URL(s)"]
    ws2.append(headers2)
    style_header(ws2, ncols=len(headers2))
    ws2.freeze_panes = "A2"

    by_name = {}
    for c in CANDIDATES:
        by_name[c["name"]] = c

    def find_candidate(substr):
        for name, c in by_name.items():
            if substr in name:
                return c
        return None

    for substr, cat, note in TOP_PICKS:
        c = find_candidate(substr)
        if c is None:
            continue
        ws2.append([note, cat, c["name"], c["expertise"], c["why_fit"], c["depth"],
                    c["socials"], c["sources"]])
    for row in ws2.iter_rows(min_row=2, max_row=ws2.max_row, max_col=len(headers2)):
        for cell in row:
            cell.border = border
            cell.alignment = Alignment(vertical="top", wrap_text=True)
    autosize(ws2, max_width=50)

    # ---------------- Verticals & Gaps ----------------
    ws3 = wb.create_sheet("Verticals & Gaps")
    ws3["A1"] = "Career-Vertical Priority Ranking (which verticals to attack)"
    ws3["A1"].font = Font(name=FONT_NAME, bold=True, size=13)
    ws3.append([])
    ws3.append(["Vertical", "Notes"])
    style_header(ws3, row=ws3.max_row, ncols=2)
    for vert, note in VERTICAL_RANKING:
        ws3.append([vert, note])

    ws3.append([])
    r = ws3.max_row + 1
    ws3.cell(row=r, column=1, value="Honest Gaps (no credible named individual found)").font = Font(name=FONT_NAME, bold=True, size=13)
    ws3.append([])
    ws3.append(["Gap", "Notes"])
    style_header(ws3, row=ws3.max_row, ncols=2)
    for gap, note in HONEST_GAPS:
        ws3.append([gap, note])

    ws3.append([])
    r = ws3.max_row + 1
    ws3.cell(row=r, column=1, value="Excluded During Research (namesake traps / disqualified leads)").font = Font(name=FONT_NAME, bold=True, size=13)
    ws3.append([])
    ws3.append(["Name", "Category", "Reason Excluded"])
    style_header(ws3, row=ws3.max_row, ncols=3)
    for e in EXCLUDED:
        ws3.append([e["name"], e["category"], e["reason"]])

    for row in ws3.iter_rows(min_row=1, max_row=ws3.max_row, max_col=3):
        for cell in row:
            if cell.value is not None:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
    autosize(ws3, max_width=60)

    # ---------------- Method ----------------
    ws4 = wb.create_sheet("Method")
    ws4["A1"] = "Method, Rules & Counts"
    ws4["A1"].font = Font(name=FONT_NAME, bold=True, size=13)
    ws4.append([])
    ws4.append(["Metric", "Value"])
    style_header(ws4, row=ws4.max_row, ncols=2)
    ws4.append(["Total candidate rows in 'All Candidates'", n_total])
    ws4.append(["Disqualified (kept for transparency, status = DQ)", n_dq])
    ws4.append(["Cross-listed by 2+ scouts (convergence signal)", n_crosslisted])
    ws4.append(["Explicitly excluded during research (namesake traps etc.)", len(EXCLUDED)])
    ws4.append(["Scout categories", 6])
    ws4.append([])

    r = ws4.max_row + 1
    ws4.cell(row=r, column=1, value="Notes").font = Font(name=FONT_NAME, bold=True, size=12)
    ws4.append([])
    for note in METHOD_NOTES:
        note = note.format(n_raw=n_total, n_distinct=n_total - n_dq)
        ws4.append([note])
        ws4.cell(row=ws4.max_row, column=1).alignment = Alignment(wrap_text=True, vertical="top")
        ws4.merge_cells(start_row=ws4.max_row, start_column=1, end_row=ws4.max_row, end_column=6)

    ws4.column_dimensions["A"].width = 110
    ws4.column_dimensions["B"].width = 14
    for row in ws4.iter_rows(min_row=1, max_row=8, max_col=2):
        for cell in row:
            if cell.value is not None:
                cell.alignment = Alignment(vertical="top", wrap_text=True)

    set_default_font(wb["All Candidates"])
    set_default_font(wb["Top Picks"])
    set_default_font(wb["Verticals & Gaps"])
    set_default_font(wb["Method"])

    out_path = "NH_Expert_Creator_Scout.xlsx"
    wb.save(out_path)
    print(f"Wrote {out_path}: {n_total} candidates, {len(TOP_PICKS)} top picks.")


if __name__ == "__main__":
    main()
